(()=>{'use strict';
function styles(){if(document.getElementById('calendarShareStyles'))return;const s=document.createElement('style');s.id='calendarShareStyles';s.textContent=`.calendar-share-wrap{display:flex;justify-content:flex-end;margin:8px 0}.calendar-share-button{min-height:32px;border:0;border-radius:10px;background:#eff6ff;color:#175cd3;font-weight:800;font-size:.72rem;padding:0 12px}.calendar-share-panel{display:none;margin:8px 0 12px;padding:12px;border:1px solid #bfdbfe;border-radius:13px;background:#eff6ff}.calendar-share-panel.open{display:block}.calendar-share-panel h4{margin:0 0 8px}.calendar-share-options{display:grid;gap:7px}.calendar-share-option{display:flex;align-items:center;gap:9px;padding:7px 8px;border-radius:10px;background:#fff}.calendar-share-option input{appearance:none;width:20px;height:20px;border:2px solid #2563eb;border-radius:50%;margin:0;display:grid;place-content:center}.calendar-share-option input:checked:after{content:'';width:10px;height:10px;border-radius:50%;background:#2563eb}.calendar-share-actions{display:flex;gap:8px;margin-top:10px}.calendar-share-actions button{flex:1;min-height:38px;border-radius:10px;border:0;font-weight:800}.calendar-share-confirm{background:#2563eb;color:#fff}.calendar-share-cancel{background:#fff;color:#334155;border:1px solid #dbe3ee!important}`;document.head.append(s)}
function panel(){return document.querySelector('[data-screen-panel="calendar"] .calendar-section')}
function monthLabel(){const m=document.getElementById('calendarMonth')?.selectedOptions?.[0]?.textContent||'',y=document.getElementById('calendarYear')?.value||'';return [m,y].filter(Boolean).join(' de ')}
function sharePanel(){let p=document.getElementById('calendarSharePanel');if(p)return p;const wrap=document.getElementById('calendarShareWrap');if(!wrap)return null;p=document.createElement('div');p.id='calendarSharePanel';p.className='calendar-share-panel';wrap.insertAdjacentElement('afterend',p);return p}
function openShare(){const p=sharePanel();if(!p)return;const details=document.getElementById('calendarDetails');const detailText=(details?.innerText||'').trim();const hasDetails=detailText&&!/toque em um dia/i.test(detailText);p.innerHTML='<h4>Selecionar páginas para compartilhar</h4><div class="calendar-share-options"></div><div class="calendar-share-actions"><button type="button" class="calendar-share-cancel">Cancelar</button><button type="button" class="calendar-share-confirm">Compartilhar</button></div>';const o=p.querySelector('.calendar-share-options');const all=document.createElement('label');all.className='calendar-share-option';all.innerHTML='<input type="checkbox" data-all><span>Todas as páginas</span>';o.append(all);const cal=document.createElement('label');cal.className='calendar-share-option';cal.innerHTML=`<input type="checkbox" data-calendar-page="calendar" checked><span>Calendário — ${monthLabel()}</span>`;o.append(cal);if(hasDetails){const det=document.createElement('label');det.className='calendar-share-option';det.innerHTML='<input type="checkbox" data-calendar-page="details"><span>Detalhes do dia selecionado</span>';o.append(det)}all.querySelector('input').onchange=()=>o.querySelectorAll('[data-calendar-page]').forEach(x=>x.checked=all.querySelector('input').checked);p.querySelector('.calendar-share-cancel').onclick=()=>p.classList.remove('open');p.classList.add('open')}
function apply(){styles();const sec=panel();if(!sec||document.getElementById('calendarShareButton'))return;const toolbar=sec.querySelector('.calendar-toolbar');const wrap=document.createElement('div');wrap.id='calendarShareWrap';wrap.className='calendar-share-wrap';wrap.innerHTML='<button id="calendarShareButton" type="button" class="calendar-share-button">↗ Compartilhar</button>';toolbar?.insertAdjacentElement('afterend',wrap);wrap.querySelector('button').onclick=openShare}
function boot(){apply();document.querySelector('[data-screen="calendar"]')?.addEventListener('click',()=>setTimeout(apply,30));new MutationObserver(apply).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();