(()=>{'use strict';
function styles(){if(document.getElementById('calendarShareStyles'))return;const s=document.createElement('style');s.id='calendarShareStyles';s.textContent='.calendar-share-wrap{display:flex;justify-content:flex-end;margin:8px 0 10px}.calendar-share-button{min-height:32px;border:0;border-radius:10px;background:#eff6ff;color:#175cd3;font-weight:800;font-size:.72rem;padding:0 12px}';document.head.append(s)}
function section(){return document.querySelector('[data-screen-panel="calendar"] .calendar-section')}
function propertyLabel(){return document.getElementById('propertyName')?.textContent?.trim()||'Propriedade'}
function periodLabel(){const m=document.getElementById('calendarMonth')?.selectedOptions?.[0]?.textContent?.trim()||'',y=document.getElementById('calendarYear')?.selectedOptions?.[0]?.textContent?.trim()||document.getElementById('calendarYear')?.value||'';return [m,y].filter(Boolean).join(' de ')}
async function share(){const sec=section();if(!sec)return;const period=periodLabel()||'período selecionado';try{await window.StayPdf?.sharePdf({title:'Calendário - Stay in Control 1.0',filename:`Stay-Control-Calendario-${period}`,pages:[{title:`Calendário — ${period}`,subtitle:propertyLabel(),element:sec}]})}catch(e){console.error(e);alert('Não foi possível gerar o PDF do calendário agora.')}}
function apply(){styles();const sec=section();if(!sec||document.getElementById('calendarShareButton'))return;const toolbar=sec.querySelector('.calendar-toolbar');const wrap=document.createElement('div');wrap.id='calendarShareWrap';wrap.className='calendar-share-wrap';wrap.innerHTML='<button id="calendarShareButton" type="button" class="calendar-share-button">↗ Compartilhar</button>';toolbar?.insertAdjacentElement('afterend',wrap);wrap.querySelector('button').onclick=share}
function boot(){apply();document.querySelector('[data-screen="calendar"]')?.addEventListener('click',()=>setTimeout(apply,30));new MutationObserver(apply).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();