(()=>{'use strict';
const KEY='stay-control-support-tickets-v1',AUTH='ap207-auth-profile-v1';
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}}
function save(v){localStorage.setItem(KEY,JSON.stringify(v));window.dispatchEvent(new CustomEvent('stay-support-updated'))}
function profile(){return read(AUTH,{profile:{role:'super_admin',name:'Super Administrador'}}).profile||{role:'super_admin',name:'Super Administrador'}}
function tickets(){return read(KEY,[])}
function protocol(){const d=new Date(),date=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}`;return`SIC-${date}-${String(Date.now()).slice(-6)}`}
function now(){return new Date().toLocaleString('pt-BR')}
function canUseSupport(p){return p.role==='admin'||p.role==='super_admin'}
function actor(p=profile()){return p.name||p.email||(p.role==='super_admin'?'Super Administrador':'Administrador')}
function isClosed(t){return t.status==='Encerrado'||t.status==='Resolvido'}
function notify(title,body){try{if(!('Notification'in window))return;if(Notification.permission==='granted')new Notification(title,{body});}catch{}}
function requestNotifications(){try{if('Notification'in window&&Notification.permission==='default')Notification.requestPermission()}catch{}}
function visible(all,p){if(p.role==='super_admin')return all;return all.filter(t=>t.createdBy===actor(p))}
function markRead(t,p){t.readBy=t.readBy||{};t.readBy[actor(p)]=Date.now()}
function unreadFor(t,p){const last=Math.max(...(t.messages||[]).map(m=>Number(m.ts)||0),Number(t.createdTs)||0);return last>(t.readBy?.[actor(p)]||0)&&((t.messages||[]).some(m=>m.by!==actor(p))||t.createdBy!==actor(p))}
function updateBadge(){const p=profile();if(!canUseSupport(p))return;const n=visible(tickets(),p).filter(t=>unreadFor(t,p)&&!isClosed(t)).length;let badge=document.getElementById('supportUnreadBadge');if(!badge){badge=document.createElement('div');badge.id='supportUnreadBadge';badge.style.cssText='position:fixed;right:14px;bottom:86px;z-index:50;min-width:34px;height:34px;padding:0 9px;border-radius:18px;background:#b42318;color:#fff;font-weight:800;display:flex;align-items:center;justify-content:center;box-shadow:0 5px 18px rgba(0,0,0,.2)';document.body.append(badge)}badge.textContent=n?String(n):'';badge.hidden=!n}
function startDictation(textarea,button){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Ditado por voz não está disponível neste navegador.');return}const r=new SR();r.lang='pt-BR';r.interimResults=false;r.continuous=false;button.textContent='🎙️ Ouvindo…';r.onresult=e=>{const txt=[...e.results].map(x=>x[0].transcript).join(' ');textarea.value=(textarea.value?textarea.value.trim()+' ':'')+txt;textarea.focus()};r.onerror=()=>{button.textContent='🎤 Falar'};r.onend=()=>{button.textContent='🎤 Falar'};r.start()}
function inject(){if(document.getElementById('supportCenter'))return;const p=profile();if(!canUseSupport(p))return;const home=document.querySelector('[data-screen-panel="home"]');if(!home)return;requestNotifications();const box=document.createElement('section');box.id='supportCenter';box.className='panel support-center';box.innerHTML=`<div class="panel-heading"><div><p class="eyebrow">Customer Service</p><h2>Central de Atendimento <span id="supportHeadingBadge"></span></h2><p class="admin-intro">Área exclusiva para administradores. Chamados, respostas, protocolo e histórico ficam registrados aqui.</p></div><button id="newTicket" class="button button-primary" type="button">Novo chamado</button></div><form id="ticketForm" class="expense-form" hidden><div class="field"><label>Categoria</label><select id="ticketCategory"><option>Problema no aplicativo</option><option>Login/Acesso</option><option>Reserva</option><option>Relatório</option><option>Integração</option><option>Pagamento</option><option>Outro</option></select></div><div class="field field-wide"><label>Assunto</label><input id="ticketSubject" maxlength="100" required></div><div class="field field-wide"><label>Descrição do problema</label><textarea id="ticketDescription" required></textarea></div><div class="form-actions field-wide"><button class="button button-primary" type="submit">Criar protocolo</button><button id="cancelTicket" class="button button-secondary" type="button">Cancelar</button></div></form><div id="supportStats" class="report-metrics"></div><div id="ticketList"></div>`;home.append(box);
const form=box.querySelector('#ticketForm');box.querySelector('#newTicket').onclick=()=>{form.hidden=false;box.querySelector('#ticketSubject').focus()};box.querySelector('#cancelTicket').onclick=()=>form.hidden=true;form.onsubmit=e=>{e.preventDefault();const all=tickets(),user=profile(),who=actor(user),ts=Date.now(),t={id:protocol(),category:box.querySelector('#ticketCategory').value,subject:box.querySelector('#ticketSubject').value.trim(),description:box.querySelector('#ticketDescription').value.trim(),status:'Aberto',createdAt:now(),createdTs:ts,updatedAt:now(),createdBy:who,createdByRole:user.role,assignedTo:null,messages:[],readBy:{[who]:ts},history:[{at:now(),by:who,action:'Chamado aberto'}]};if(!t.subject||!t.description)return;all.unshift(t);save(all);form.reset();form.hidden=true;notify('Novo chamado no Stay in Control',`${t.id} — ${t.subject}`);render(box)};render(box)}
function render(box){const p=profile(),all=visible(tickets(),p),counts=s=>all.filter(t=>t.status===s).length,unread=all.filter(t=>unreadFor(t,p)&&!isClosed(t)).length;const hb=box.querySelector('#supportHeadingBadge');hb.textContent=unread?`(${unread} nova${unread>1?'s':''})`:'';box.querySelector('#supportStats').innerHTML=`<div><small>Abertos</small><strong>${counts('Aberto')}</strong></div><div><small>Em atendimento</small><strong>${counts('Em atendimento')}</strong></div><div><small>Aguardando administrador</small><strong>${counts('Aguardando administrador')}</strong></div><div><small>Encerrados</small><strong>${counts('Resolvido')+counts('Encerrado')}</strong></div>`;
box.querySelector('#ticketList').innerHTML=all.map(t=>{const closed=isClosed(t),mine=t.assignedTo===actor(p),newMark=unreadFor(t,p)?'<span style="color:#b42318;font-weight:800"> • NOVA MENSAGEM</span>':'';return `<article class="booking support-ticket" data-ticket-card="${t.id}"><div class="bookingtop"><div><span class="guest">Protocolo ${t.id}${newMark}</span><strong>${t.subject}</strong><p>${t.category} · Aberto por ${t.createdBy} · ${t.createdAt}</p>${t.assignedTo?`<p><b>Em atendimento por:</b> ${t.assignedTo}</p>`:''}</div><span class="status ${closed?'status-confirmada':''}">${t.status}</span></div><p>${t.description}</p><div style="margin:12px 0">${(t.messages||[]).map(m=>`<div style="padding:10px 12px;margin:7px 0;border-radius:12px;background:rgba(248,250,252,.92)"><small>${m.at} · ${m.by}</small><br>${m.text}</div>`).join('')}</div>${!closed?`<div class="field"><label>Responder</label><textarea data-reply="${t.id}" placeholder="Digite a resposta ou use o microfone"></textarea></div><div class="booking-actions"><button class="button button-secondary" type="button" data-dictate="${t.id}">🎤 Falar</button><button class="button button-primary" type="button" data-send="${t.id}">Enviar resposta</button>${p.role==='super_admin'&&!mine?`<button class="button button-secondary" type="button" data-claim="${t.id}">Assumir atendimento</button>`:''}${p.role==='super_admin'?`<button class="button button-secondary" type="button" data-status-id="${t.id}" data-status="Aguardando administrador">Aguardando administrador</button>`:''}<button class="button button-secondary" type="button" data-end-ticket="${t.id}">Encerrar atendimento</button></div>`:''}<details><summary>Histórico (${t.history?.length||0})</summary>${(t.history||[]).map(h=>`<p><small>${h.at} · ${h.by}</small><br>${h.action}</p>`).join('')}</details></article>`}).join('')||'<p>Nenhum chamado registrado.</p>';
box.querySelectorAll('[data-ticket-card]').forEach(card=>{const allT=tickets(),t=allT.find(x=>x.id===card.dataset.ticketCard);if(t){markRead(t,p);saveSilent(allT)}});box.querySelectorAll('[data-dictate]').forEach(b=>b.onclick=()=>startDictation(box.querySelector(`[data-reply="${b.dataset.dictate}"]`),b));box.querySelectorAll('[data-send]').forEach(b=>b.onclick=()=>sendReply(b.dataset.send,box));box.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>claim(b.dataset.claim,box));box.querySelectorAll('[data-status-id]').forEach(b=>b.onclick=()=>change(b.dataset.statusId,b.dataset.status,box));box.querySelectorAll('[data-end-ticket]').forEach(b=>b.onclick=()=>endTicket(b.dataset.endTicket,box));updateBadge()}
function saveSilent(v){localStorage.setItem(KEY,JSON.stringify(v))}
function sendReply(id,box){const p=profile(),ta=box.querySelector(`[data-reply="${id}"]`),text=ta?.value.trim();if(!text)return;const all=tickets(),t=all.find(x=>x.id===id);if(!t)return;const who=actor(p),ts=Date.now();t.messages=t.messages||[];t.messages.push({at:now(),ts,by:who,role:p.role,text});t.updatedAt=now();t.status=p.role==='super_admin'?'Aguardando administrador':'Em atendimento';t.history=t.history||[];t.history.push({at:now(),by:who,action:'Nova mensagem enviada'});markRead(t,p);save(all);notify('Nova mensagem de suporte',`${t.id} — ${who} respondeu`);render(box)}
function claim(id,box){const all=tickets(),t=all.find(x=>x.id===id);if(!t)return;t.assignedTo=actor();t.status='Em atendimento';t.updatedAt=now();t.history=t.history||[];t.history.push({at:now(),by:actor(),action:'Atendimento assumido'});save(all);render(box)}
function change(id,status,box){const all=tickets(),t=all.find(x=>x.id===id);if(!t)return;t.status=status;t.updatedAt=now();t.history=t.history||[];t.history.push({at:now(),by:actor(),action:`Status alterado para ${status}`});save(all);render(box)}
function endTicket(id,box){if(!window.confirm('Deseja encerrar este atendimento? O histórico continuará salvo.'))return;const all=tickets(),t=all.find(x=>x.id===id);if(!t)return;t.status='Encerrado';t.updatedAt=now();t.closedAt=now();t.closedBy=actor();t.history=t.history||[];t.history.push({at:now(),by:t.closedBy,action:'Atendimento encerrado'});save(all);render(box)}
window.addEventListener('storage',e=>{if(e.key===KEY){const box=document.getElementById('supportCenter');if(box){render(box);notify('Nova atividade no suporte','Há uma nova mensagem ou atualização de chamado.')}}});
window.addEventListener('stay-support-updated',updateBadge);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(inject,650));else setTimeout(inject,650)})();