(()=>{'use strict';
const AUTH='ap207-auth-profile-v1',READ_KEY='stay-control-support-read-v2';
let box=null,client=null,currentUser=null,realtime=null,lastSnapshot='';
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}}
function profile(){return read(AUTH,{profile:{role:'super_admin',name:'Super Administrador'}}).profile||{role:'super_admin',name:'Super Administrador'}}
function actor(p=profile()){return p.name||p.email||(p.role==='super_admin'?'Super Administrador':'Administrador')}
function canUseSupport(p){return p.role==='admin'||p.role==='super_admin'}
function isSuper(){return profile().role==='super_admin'}
function isClosed(t){return t.status==='Encerrado'||t.status==='Resolvido'}
function protocol(){const d=new Date(),date=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}`;return`SIC-${date}-${String(Date.now()).slice(-6)}`}
function fmt(iso){try{return new Date(iso).toLocaleString('pt-BR')}catch{return iso||''}}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function readMarks(){return read(READ_KEY,{})}
function markRead(id){const all=readMarks();all[`${profile().id||actor()}:${id}`]=Date.now();localStorage.setItem(READ_KEY,JSON.stringify(all))}
function lastActivity(t){return Math.max(new Date(t.updated_at||t.created_at||0).getTime(),...(t.messages||[]).map(m=>new Date(m.created_at||0).getTime()))}
function unread(t){const marks=readMarks(),seen=marks[`${profile().id||actor()}:${t.id}`]||0;if(lastActivity(t)<=seen)return false;if(isSuper())return t.created_by!==profile().id||(t.messages||[]).some(m=>m.sender_id!==profile().id&&new Date(m.created_at).getTime()>seen);return (t.messages||[]).some(m=>m.sender_id!==profile().id&&new Date(m.created_at).getTime()>seen)}
function notify(title,body){try{if('Notification'in window&&Notification.permission==='granted')new Notification(title,{body})}catch{}}
function requestNotifications(){try{if('Notification'in window&&Notification.permission==='default')Notification.requestPermission()}catch{}}
function styles(){if(document.getElementById('staySupportStyles'))return;const s=document.createElement('style');s.id='staySupportStyles';s.textContent=`.support-center{margin-top:18px}.support-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:14px 0}.support-summary>div{padding:14px;border-radius:14px;background:rgba(248,250,252,.94);border:1px solid #e2e8f0}.support-summary small{display:block;color:#64748b}.support-summary strong{font-size:1.5rem}.support-ticket{border-left:4px solid #2563eb}.support-ticket.support-unread{border-left-color:#dc2626;box-shadow:0 0 0 2px rgba(220,38,38,.08)}.support-open-pill{display:inline-flex;align-items:center;gap:7px;padding:7px 11px;border-radius:999px;background:#fee2e2;color:#991b1b;font-weight:800;font-size:.82rem}.support-message{padding:10px 12px;margin:7px 0;border-radius:12px;background:rgba(248,250,252,.92)}.support-message.mine{background:#eff6ff}.support-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.support-floating-badge{position:fixed;right:14px;bottom:86px;z-index:50;min-width:38px;height:38px;padding:0 10px;border-radius:20px;background:#b42318;color:#fff;font-weight:800;display:flex;align-items:center;justify-content:center;box-shadow:0 5px 18px rgba(0,0,0,.22)}@media(max-width:700px){.support-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.support-actions .button{flex:1 1 145px}}`;document.head.append(s)}
async function initClient(){for(let i=0;i<80;i++){if(window.AP207Supabase){client=window.AP207Supabase;break}await new Promise(r=>setTimeout(r,150))}if(!client)throw new Error('O serviço de suporte ainda está carregando.');const {data:{user}}=await client.auth.getUser();currentUser=user;return user}
async function loadTickets(){if(!client)return[];const {data:ts,error}=await client.from('support_tickets').select('*').order('created_at',{ascending:false});if(error)throw error;const ids=(ts||[]).map(t=>t.id);let msgs=[];if(ids.length){const {data,error:e}=await client.from('support_messages').select('*').in('ticket_id',ids).order('created_at',{ascending:true});if(e)throw e;msgs=data||[]}return (ts||[]).map(t=>({...t,messages:msgs.filter(m=>m.ticket_id===t.id)}))}
function updateBadge(tickets){const open=tickets.filter(t=>!isClosed(t)).length,un=tickets.filter(t=>!isClosed(t)&&unread(t)).length;let badge=document.getElementById('supportUnreadBadge');if(!badge){badge=document.createElement('div');badge.id='supportUnreadBadge';badge.className='support-floating-badge';document.body.append(badge)}const value=isSuper()?open:un;badge.textContent=value?String(value):'';badge.hidden=!value;badge.title=isSuper()?`${open} chamado(s) em aberto`:`${un} nova(s) mensagem(ns)`}
function startDictation(textarea,button){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Ditado por voz não está disponível neste navegador.');return}const r=new SR();r.lang='pt-BR';r.interimResults=false;r.continuous=false;button.textContent='🎙️ Ouvindo…';r.onresult=e=>{const txt=[...e.results].map(x=>x[0].transcript).join(' ');textarea.value=(textarea.value?textarea.value.trim()+' ':'')+txt;textarea.focus()};r.onend=()=>button.textContent='🎤 Falar';r.onerror=()=>button.textContent='🎤 Falar';r.start()}
function install(){if(document.getElementById('supportCenter'))return;const p=profile();if(!canUseSupport(p))return;const home=document.querySelector('[data-screen-panel="home"]');if(!home)return;styles();requestNotifications();box=document.createElement('section');box.id='supportCenter';box.className='panel support-center';box.innerHTML=`<div class="panel-heading"><div><p class="eyebrow">Suporte técnico</p><h2>${p.role==='super_admin'?'Chamados em aberto':'Central de Atendimento'} <span id="supportHeadingBadge"></span></h2><p class="admin-intro">${p.role==='super_admin'?'Quando um administrador abrir um chamado, ele aparecerá aqui para você responder.':'Abra um chamado para falar com o suporte do Stay in Control.'}</p></div>${p.role==='admin'?'<button id="newTicket" class="button button-primary" type="button">Novo chamado</button>':''}</div><form id="ticketForm" class="expense-form" hidden><div class="field"><label>Categoria</label><select id="ticketCategory"><option>Problema no aplicativo</option><option>Login/Acesso</option><option>Reserva</option><option>Relatório</option><option>Integração</option><option>Pagamento</option><option>Outro</option></select></div><div class="field field-wide"><label>Assunto</label><input id="ticketSubject" maxlength="100" required></div><div class="field field-wide"><label>Descrição do problema</label><textarea id="ticketDescription" required></textarea></div><div class="form-actions field-wide"><button class="button button-primary" type="submit">Criar chamado</button><button id="cancelTicket" class="button button-secondary" type="button">Cancelar</button></div></form><div id="supportStats" class="support-summary"></div><div id="ticketList"><p>Carregando chamados…</p></div>`;home.append(box);
 if(p.role==='admin'){const form=box.querySelector('#ticketForm');box.querySelector('#newTicket').onclick=()=>{form.hidden=false;box.querySelector('#ticketSubject').focus()};box.querySelector('#cancelTicket').onclick=()=>form.hidden=true;form.onsubmit=createTicket}
 refresh(true);subscribe();setInterval(()=>refresh(false),15000)}
async function createTicket(e){e.preventDefault();const form=e.currentTarget,subject=box.querySelector('#ticketSubject').value.trim(),description=box.querySelector('#ticketDescription').value.trim();if(!subject||!description)return;const p=profile();const row={protocol:protocol(),category:box.querySelector('#ticketCategory').value,subject,description,status:'Aberto',created_by:currentUser.id,created_by_name:actor(p),created_by_email:p.email||currentUser.email||'',created_by_role:p.role};const {error}=await client.from('support_tickets').insert(row);if(error){alert(`Não foi possível abrir o chamado: ${error.message}`);return}form.reset();form.hidden=true;await refresh(true)}
async function refresh(markVisible){if(!box||!client)return;try{const all=await loadTickets();const snap=JSON.stringify(all.map(t=>[t.id,t.status,t.updated_at,(t.messages||[]).length]));if(lastSnapshot&&snap!==lastSnapshot&&isSuper()){const changed=all.find(t=>!isClosed(t)&&unread(t));if(changed)notify('Novo chamado no Stay in Control',`${changed.protocol} — ${changed.subject}`)}lastSnapshot=snap;render(all,markVisible)}catch(err){box.querySelector('#ticketList').innerHTML=`<p style="color:#b42318">Não foi possível carregar os chamados: ${esc(err.message)}</p>`}}
function render(all,markVisible=false){const open=all.filter(t=>!isClosed(t)),un=all.filter(t=>!isClosed(t)&&unread(t));box.querySelector('#supportHeadingBadge').innerHTML=isSuper()&&open.length?`<span class="support-open-pill">${open.length} aberto${open.length>1?'s':''}</span>`:un.length?`<span class="support-open-pill">${un.length} nova${un.length>1?'s':''}</span>`:'';const count=s=>all.filter(t=>t.status===s).length;box.querySelector('#supportStats').innerHTML=`<div><small>Abertos</small><strong>${count('Aberto')}</strong></div><div><small>Em atendimento</small><strong>${count('Em atendimento')}</strong></div><div><small>Aguardando resposta</small><strong>${count('Aguardando administrador')+count('Aguardando suporte')}</strong></div><div><small>Encerrados</small><strong>${all.filter(isClosed).length}</strong></div>`;
 const list=isSuper()?[...open,...all.filter(isClosed)]:all;box.querySelector('#ticketList').innerHTML=list.map(t=>{const closed=isClosed(t),isNew=unread(t),mine=t.assigned_to===profile().id;return `<article class="booking support-ticket ${isNew?'support-unread':''}" data-ticket="${t.id}"><div class="bookingtop"><div><span class="guest">${esc(t.protocol)}${isNew?' • NOVO':''}</span><strong>${esc(t.subject)}</strong><p>${esc(t.category)} · Aberto por ${esc(t.created_by_name||t.created_by_email||'Administrador')} · ${fmt(t.created_at)}</p>${t.assigned_to_name?`<p><b>Em atendimento por:</b> ${esc(t.assigned_to_name)}</p>`:''}</div><span class="status">${esc(t.status)}</span></div><p>${esc(t.description)}</p><div>${(t.messages||[]).map(m=>`<div class="support-message ${m.sender_id===profile().id?'mine':''}"><small>${fmt(m.created_at)} · ${esc(m.sender_name||'Usuário')}</small><br>${esc(m.body)}</div>`).join('')}</div>${!closed?`<div class="field"><label>Responder</label><textarea data-reply="${t.id}" placeholder="Digite sua resposta ou use o microfone"></textarea></div><div class="support-actions"><button class="button button-secondary" type="button" data-dictate="${t.id}">🎤 Falar</button><button class="button button-primary" type="button" data-send="${t.id}">Enviar resposta</button>${isSuper()&&!mine?`<button class="button button-secondary" type="button" data-claim="${t.id}">Assumir atendimento</button>`:''}${isSuper()?`<button class="button button-secondary" type="button" data-end="${t.id}">Encerrar atendimento</button>`:''}</div>`:''}</article>`}).join('')||'<p>Nenhum chamado registrado.</p>';
 box.querySelectorAll('[data-dictate]').forEach(b=>b.onclick=()=>startDictation(box.querySelector(`[data-reply="${b.dataset.dictate}"]`),b));box.querySelectorAll('[data-send]').forEach(b=>b.onclick=()=>sendReply(b.dataset.send));box.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>claim(b.dataset.claim));box.querySelectorAll('[data-end]').forEach(b=>b.onclick=()=>endTicket(b.dataset.end));if(markVisible)open.forEach(t=>markRead(t.id));updateBadge(all)}
async function sendReply(id){const ta=box.querySelector(`[data-reply="${id}"]`),text=ta?.value.trim();if(!text)return;const p=profile();const {error}=await client.from('support_messages').insert({ticket_id:id,sender_id:currentUser.id,sender_name:actor(p),sender_role:p.role,body:text});if(error){alert(`Não foi possível enviar: ${error.message}`);return}const status=isSuper()?'Aguardando administrador':'Aguardando suporte';await client.from('support_tickets').update({status,updated_at:new Date().toISOString()}).eq('id',id);markRead(id);await refresh(false)}
async function claim(id){const p=profile();const {error}=await client.from('support_tickets').update({assigned_to:currentUser.id,assigned_to_name:actor(p),status:'Em atendimento',updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else refresh(false)}
async function endTicket(id){if(!confirm('Deseja encerrar este atendimento? O histórico continuará salvo.'))return;const p=profile();const {error}=await client.from('support_tickets').update({status:'Encerrado',closed_at:new Date().toISOString(),closed_by:currentUser.id,closed_by_name:actor(p),updated_at:new Date().toISOString()}).eq('id',id);if(error)alert(error.message);else refresh(false)}
function subscribe(){if(!client||realtime)return;realtime=client.channel(`stay-support-${profile().id||Date.now()}`).on('postgres_changes',{event:'*',schema:'public',table:'support_tickets'},payload=>{if(isSuper()&&payload.eventType==='INSERT')notify('Novo chamado no Stay in Control',`${payload.new?.protocol||'Novo chamado'} — ${payload.new?.subject||''}`);refresh(false)}).on('postgres_changes',{event:'INSERT',schema:'public',table:'support_messages'},()=>refresh(false)).subscribe()}
async function boot(){const p=profile();if(!canUseSupport(p))return;try{await initClient();install()}catch(e){console.error(e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,650));else setTimeout(boot,650)})();