(()=>{'use strict';
let page=0,rendering=false;
function styles(){if(document.getElementById('expensePagesStyles'))return;const s=document.createElement('style');s.id='expensePagesStyles';s.textContent=`
.expense-page-toolbar{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:10px;margin:14px 0 10px;padding:10px 12px;border:1px solid #dbe3ee;border-radius:14px;background:#fff}.expense-page-toolbar button{min-height:42px;border:1px solid #dbe3ee;border-radius:11px;background:#fff;padding:0 12px;font-weight:800;color:#172033}.expense-page-toolbar button:disabled{opacity:.38}.expense-page-label{text-align:center}.expense-page-label strong{display:block;font-size:.9rem}.expense-page-label span{display:block;margin-top:2px;color:#667085;font-size:.72rem}.expense-page-hidden{display:none!important}@media(max-width:520px){.expense-page-toolbar{gap:8px;padding:9px}.expense-page-toolbar button{min-width:86px;padding:0 8px}.expense-page-label strong{font-size:.82rem}.expense-page-label span{font-size:.66rem}}
`;document.head.append(s)}
function container(){return document.getElementById('expenses')}
function items(){const c=container();return c?[...c.children].filter(el=>el.nodeType===1&&!el.classList.contains('expense-page-toolbar')):[]}
function toolbar(){let b=document.getElementById('expensePageToolbar');if(b)return b;const c=container();if(!c)return null;b=document.createElement('div');b.id='expensePageToolbar';b.className='expense-page-toolbar';b.innerHTML='<button type="button" data-prev>← Voltar</button><div class="expense-page-label"><strong id="expensePageCount">Página 1</strong><span id="expensePageName">Despesa</span></div><button type="button" data-next>Próximo →</button>';c.insertAdjacentElement('beforebegin',b);b.querySelector('[data-prev]').onclick=()=>{if(page>0){page--;render();scrollTop()}};b.querySelector('[data-next]').onclick=()=>{const total=items().length;if(page<total-1){page++;render();scrollTop()}};return b}
function scrollTop(){document.getElementById('expensesSection')?.scrollIntoView({behavior:'smooth',block:'start'})}
function labelFor(el,index){const text=[...el.querySelectorAll('strong,b')].map(x=>x.textContent.trim()).find(Boolean)||'';const category=[...el.querySelectorAll('*')].find(x=>x.childElementCount===0&&/categoria/i.test(x.previousElementSibling?.textContent||''))?.textContent||'';return category||text||`Despesa ${index+1}`}
function render(){if(rendering)return;rendering=true;requestAnimationFrame(()=>{const list=items(),b=toolbar();if(!b){rendering=false;return}if(!list.length){b.style.display='none';rendering=false;return}b.style.display='grid';page=Math.max(0,Math.min(page,list.length-1));list.forEach((el,i)=>el.classList.toggle('expense-page-hidden',i!==page));b.querySelector('[data-prev]').disabled=page===0;b.querySelector('[data-next]').disabled=page===list.length-1;b.querySelector('#expensePageCount').textContent=`Página ${page+1} de ${list.length}`;b.querySelector('#expensePageName').textContent=labelFor(list[page],page);rendering=false})}
function refresh(reset=false){if(reset)page=0;setTimeout(render,40)}
function boot(){styles();toolbar();render();const c=container();if(c){const mo=new MutationObserver(()=>refresh(false));mo.observe(c,{childList:true,subtree:false})}document.querySelector('[data-screen="expenses"]')?.addEventListener('click',()=>refresh(false));document.getElementById('newExpenseButton')?.addEventListener('click',()=>{items().forEach(el=>el.classList.remove('expense-page-hidden'));const b=toolbar();if(b)b.style.display='none'});document.getElementById('cancelExpenseButton')?.addEventListener('click',()=>refresh(false));document.getElementById('expenseForm')?.addEventListener('submit',()=>refresh(true));document.getElementById('propertySelector')?.addEventListener('change',()=>refresh(true))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1300),{once:true});else setTimeout(boot,1300);
})();