(()=>{'use strict';
const AUTH='ap207-auth-profile-v1',PROPS='ap207-dashboard-properties-v1',INVITES='stay-control-invitations-v1',KEY='stay-control-ical-connections-v1';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const auth=()=>read(AUTH,{}),role=()=>auth()?.profile?.role||'',props=()=>read(PROPS,{properties:[]}).properties||[],users=()=>read(INVITES,[]);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ownerFor(p){const us=users().filter(u=>u.role==='owner'&&(u.propertyIds||[]).includes(p.id));return us[0]||null}
function adminFor(p){const us=users().filter(u=>u.role==='admin'&&(u.propertyIds||[]).includes(p.id));return us[0]||null}
function allowedProps(){const a=auth(),all=props();if(role()==='super_admin')return all;const ids=new Set(a.propertyIds||[]);return all.filter(p=>ids.has(p.id))}
function style(){if(document.getElementById('icalManagerStyle'))return;const s=document.createElement('style');s.id='icalManagerStyle';s.textContent='.ical-manager{margin-top:18px}.ical-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ical-wide{grid-column:1/-1}.ical-list{display:grid;gap:10px;margin-top:16px}.ical-row{padding:14px;border:1px solid #dbe3ee;border-radius:14px;background:#fff}.ical-row small{display:block;color:#64748b;margin-top:4px;overflow-wrap:anywhere}.ical-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}@media(max-width:700px){.ical-grid{grid-template-columns:1fr}.ical-wide{grid-column:auto}}';document.head.append(s)}
function install(){if(!['admin','super_admin'].includes(role())||document.getElementById('icalManager'))return;const anchor=document.getElementById('propertySettings');if(!anchor)return;style();const sec=document.createElement('section');sec.id='icalManager';sec.className='panel ical-manager';sec.innerHTML=`<div class="panel-heading"><div><p class="eyebrow">Integração de calendário</p><h2>iCal por propriedade/unidade</h2><p class="admin-intro">Cada link fica ligado somente à unidade selecionada.</p></div></div><div class="ical-grid"><div class="field" id="icalAdminWrap"><label>Administrador</label><select id="icalAdmin"></select></div><div class="field"><label>Proprietário</label><select id="icalOwner"></select></div><div class="field"><label>Propriedade / unidade</label><select id="icalProperty"></select></div><div class="field"><label>Plataforma</label><select id="icalPlatform"><option>Airbnb</option><option>Booking.com</option><option>Vrbo</option><option>Expedia</option><option>Agoda</option><option>Outro</option></select></div><div class="field ical-wide"><label>Link iCal desta propriedade</label><input id="icalUrl" type="url" placeholder="https://.../calendar.ics"></div><div class="form-actions ical-wide"><button id="icalSave" class="button button-primary" type="button">Salvar iCal desta unidade</button></div></div><p id="icalMsg"></p><div id="icalList" class="ical-list"></div>`;anchor.insertAdjacentElement('afterend',sec);
const admin=sec.querySelector('#icalAdmin'),owner=sec.querySelector('#icalOwner'),property=sec.querySelector('#icalProperty'),url=sec.querySelector('#icalUrl'),platform=sec.querySelector('#icalPlatform'),msg=sec.querySelector('#icalMsg');
function fillAdmins(){const admins=users().filter(u=>u.role==='admin');admin.innerHTML='<option value="">Todos / sem administrador definido</option>'+admins.map(u=>`<option value="${esc(u.email)}">${esc(u.name||u.email)}</option>`).join('');sec.querySelector('#icalAdminWrap').hidden=role()!=='super_admin'}
function fillOwners(){const ps=allowedProps().filter(p=>!admin.value||adminFor(p)?.email===admin.value);const seen=new Map();ps.forEach(p=>{const o=ownerFor(p);if(o)seen.set(o.email,o)});owner.innerHTML='<option value="">Selecione o proprietário</option>'+[...seen.values()].map(o=>`<option value="${esc(o.email)}">${esc(o.name||o.email)}</option>`).join('');fillProps()}
function fillProps(){const ps=allowedProps().filter(p=>(!admin.value||adminFor(p)?.email===admin.value)&&(!owner.value||ownerFor(p)?.email===owner.value));property.innerHTML='<option value="">Selecione a propriedade/unidade</option>'+ps.map(p=>`<option value="${esc(p.id)}">${esc(p.unit||p.name||p.id)}${p.name&&p.name!==p.unit?' — '+esc(p.name):''}</option>`).join('')}
function render(){const all=read(KEY,{}),ps=new Map(props().map(p=>[p.id,p]));const rows=Object.values(all).filter(x=>role()==='super_admin'||allowedProps().some(p=>p.id===x.propertyId));sec.querySelector('#icalList').innerHTML=rows.length?rows.map(x=>{const p=ps.get(x.propertyId)||{};return `<div class="ical-row"><strong>${esc(p.unit||p.name||x.propertyId)} — ${esc(x.platform)}</strong><small>Proprietário: ${esc(x.ownerName||x.ownerEmail||'—')}</small>${role()==='super_admin'?`<small>Administrador: ${esc(x.adminName||x.adminEmail||'—')}</small>`:''}<small>${esc(x.url)}</small><div class="ical-actions"><button class="button button-secondary" type="button" data-edit="${esc(x.id)}">Editar</button><button class="button" style="background:#dc2626;color:#fff" type="button" data-del="${esc(x.id)}">Excluir</button></div></div>`}).join(''):'<small>Nenhum iCal cadastrado ainda.</small>';sec.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const x=all[b.dataset.edit];if(!x)return;admin.value=x.adminEmail||'';fillOwners();owner.value=x.ownerEmail||'';fillProps();property.value=x.propertyId;platform.value=x.platform;url.value=x.url;sec.dataset.edit=x.id;sec.scrollIntoView({behavior:'smooth',block:'center'})});sec.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(!confirm('Excluir esta conexão iCal?'))return;delete all[b.dataset.del];write(KEY,all);render()})}
admin.onchange=fillOwners;owner.onchange=fillProps;
sec.querySelector('#icalSave').onclick=()=>{const pid=property.value,u=url.value.trim();if(!pid){msg.textContent='Selecione a propriedade/unidade.';return}if(!/^https?:\/\//i.test(u)){msg.textContent='Cole um link iCal válido começando com http:// ou https://.';return}const p=props().find(x=>x.id===pid),o=ownerFor(p||{}),a=adminFor(p||{});if(role()==='admin'&&!allowedProps().some(x=>x.id===pid)){msg.textContent='Você não tem acesso a esta propriedade.';return}const all=read(KEY,{}),id=sec.dataset.edit||`${pid}::${platform.value}`;all[id]={id,propertyId:pid,propertyName:p?.name||'',unit:p?.unit||'',ownerEmail:o?.email||owner.value||'',ownerName:o?.name||'',adminEmail:a?.email||admin.value||auth()?.profile?.email||'',adminName:a?.name||auth()?.profile?.name||'',platform:platform.value,url:u,updatedAt:new Date().toISOString()};write(KEY,all);delete sec.dataset.edit;url.value='';msg.textContent='✓ iCal salvo somente para esta propriedade/unidade.';render()};fillAdmins();fillOwners();render()}
function boot(){const t=setInterval(()=>{if(document.body.classList.contains('ap207-authenticated')){install();if(document.getElementById('icalManager'))clearInterval(t)}},300);setTimeout(()=>clearInterval(t),15000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();