(()=>{'use strict';
const AUTH='ap207-auth-profile-v1',PROPS='ap207-dashboard-properties-v1',INVITES='stay-control-invitations-v1',SCOPE='stay-home-scope-v1',KEY='stay-control-ical-connections-v1';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const auth=()=>read(AUTH,{}),role=()=>auth()?.profile?.role||'',props=()=>read(PROPS,{properties:[]}).properties||[],users=()=>read(INVITES,[]),scope=()=>read(SCOPE,{});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ownerFor(p){const byId=users().find(u=>u.role==='owner'&&String(u.id||'')===String(p?.ownerId||''));if(byId)return byId;const byAccess=users().find(u=>u.role==='owner'&&(u.propertyIds||[]).includes(p?.id));return byAccess||null}
function adminFor(p){const us=users().filter(u=>u.role==='admin'&&(u.propertyIds||[]).includes(p.id));return us[0]||null}
function allowedProps(){const a=auth(),all=props();if(role()==='super_admin')return all;const ids=new Set(a.propertyIds||[]);return all.filter(p=>ids.has(p.id))}
function selectedProperty(){const s=scope();if(!s.property||s.property==='all')return null;return allowedProps().find(p=>p.id===s.property)||null}
function selectedOwnerName(p){if(p)return p.ownerName||ownerFor(p)?.name||ownerFor(p)?.email||'—';const s=scope();if(s.owner&&s.owner!=='all'){const candidate=allowedProps().find(x=>String(x.ownerId||x.ownerName)===String(s.owner));return candidate?.ownerName||s.owner}return'Todas as propriedades'}
function style(){if(document.getElementById('icalManagerStyle'))return;const s=document.createElement('style');s.id='icalManagerStyle';s.textContent='.ical-manager{margin-top:18px}.ical-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.ical-wide{grid-column:1/-1}.ical-readonly{min-height:52px;display:flex;align-items:center;padding:0 14px;border:1px solid #dbe3ee;border-radius:12px;background:#f8fafc;color:#0f172a;font-weight:700}.ical-list{display:grid;gap:10px;margin-top:16px}.ical-row{padding:14px;border:1px solid #dbe3ee;border-radius:14px;background:#fff}.ical-row small{display:block;color:#64748b;margin-top:4px;overflow-wrap:anywhere}.ical-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}@media(max-width:700px){.ical-grid{grid-template-columns:1fr}.ical-wide{grid-column:auto}}';document.head.append(s)}
function install(){if(!['admin','super_admin'].includes(role())||document.getElementById('icalManager'))return;const home=document.querySelector('[data-screen-panel="home"]');if(!home)return;style();const sec=document.createElement('section');sec.id='icalManager';sec.className='panel ical-manager';sec.innerHTML=`<div class="panel-heading"><div><p class="eyebrow">Integração de calendário</p><h2>iCal por propriedade/unidade</h2><p class="admin-intro">O proprietário e a unidade acompanham automaticamente a seleção feita na Visão Geral.</p></div></div><div class="ical-grid"><div class="field"><label>Proprietário</label><div id="icalOwnerDisplay" class="ical-readonly">—</div></div><div class="field"><label>Propriedade / unidade</label><div id="icalPropertyDisplay" class="ical-readonly">—</div></div><div class="field"><label>Plataforma</label><select id="icalPlatform"><option>Airbnb</option><option>Booking.com</option><option>Vrbo</option><option>Expedia</option><option>Agoda</option><option>Outro</option></select></div><div class="field ical-wide"><label>Link iCal desta propriedade</label><input id="icalUrl" type="url" placeholder="https://.../calendar.ics"></div><div class="form-actions ical-wide"><button id="icalSave" class="button button-primary" type="button">Salvar iCal desta unidade</button></div></div><p id="icalMsg"></p><div id="icalList" class="ical-list"></div>`;home.append(sec);
const ownerDisplay=sec.querySelector('#icalOwnerDisplay'),propertyDisplay=sec.querySelector('#icalPropertyDisplay'),url=sec.querySelector('#icalUrl'),platform=sec.querySelector('#icalPlatform'),msg=sec.querySelector('#icalMsg');
function syncSelection(){const p=selectedProperty(),s=scope();ownerDisplay.textContent=selectedOwnerName(p);propertyDisplay.textContent=p?(p.unit||p.name||p.id):(s.property==='all'?'Todas as propriedades/unidades':'Selecione uma unidade na Visão Geral');sec.dataset.propertyId=p?.id||'';if(!p)msg.textContent='Para adicionar um iCal, selecione uma propriedade/unidade específica na Visão Geral.';else if(msg.textContent.startsWith('Para adicionar'))msg.textContent=''}
function render(){const all=read(KEY,{}),ps=new Map(props().map(p=>[p.id,p]));const rows=Object.values(all).filter(x=>role()==='super_admin'||allowedProps().some(p=>p.id===x.propertyId));sec.querySelector('#icalList').innerHTML=rows.length?rows.map(x=>{const p=ps.get(x.propertyId)||{};return `<div class="ical-row"><strong>${esc(p.unit||p.name||x.propertyId)} — ${esc(x.platform)}</strong><small>Proprietário: ${esc(x.ownerName||x.ownerEmail||'—')}</small>${role()==='super_admin'?`<small>Administrador: ${esc(x.adminName||x.adminEmail||'—')}</small>`:''}<small>${esc(x.url)}</small><div class="ical-actions"><button class="button button-secondary" type="button" data-edit="${esc(x.id)}">Editar</button><button class="button" style="background:#dc2626;color:#fff" type="button" data-del="${esc(x.id)}">Remover iCal</button></div></div>`}).join(''):'<small>Nenhum iCal cadastrado ainda.</small>';sec.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const x=all[b.dataset.edit];if(!x)return;const p=props().find(y=>y.id===x.propertyId);if(p){const s=scope();write(SCOPE,{...s,owner:p.ownerId||p.ownerName||s.owner,property:p.id,propertyIds:[p.id]});window.dispatchEvent(new CustomEvent('stay:scope-change',{detail:read(SCOPE,{})}))}platform.value=x.platform;url.value=x.url;sec.dataset.edit=x.id;syncSelection();sec.scrollIntoView({behavior:'smooth',block:'center'})});sec.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(!confirm('Remover esta conexão iCal? As reservas e o histórico já registrados serão mantidos.'))return;delete all[b.dataset.del];write(KEY,all);if(sec.dataset.edit===b.dataset.del){delete sec.dataset.edit;url.value=''}msg.textContent='✓ Conexão iCal removida. O histórico de reservas foi mantido.';render()})}
sec.querySelector('#icalSave').onclick=()=>{const pid=sec.dataset.propertyId,u=url.value.trim();if(!pid){msg.textContent='Selecione uma propriedade/unidade específica na Visão Geral.';return}if(!/^https?:\/\//i.test(u)){msg.textContent='Cole um link iCal válido começando com http:// ou https://.';return}const p=props().find(x=>x.id===pid),o=ownerFor(p||{}),a=adminFor(p||{});if(role()==='admin'&&!allowedProps().some(x=>x.id===pid)){msg.textContent='Você não tem acesso a esta propriedade.';return}const all=read(KEY,{}),id=sec.dataset.edit||`${pid}::${platform.value}`;all[id]={id,propertyId:pid,propertyName:p?.name||'',unit:p?.unit||'',ownerEmail:o?.email||'',ownerName:p?.ownerName||o?.name||'',adminEmail:a?.email||auth()?.profile?.email||'',adminName:a?.name||auth()?.profile?.name||'',platform:platform.value,url:u,updatedAt:new Date().toISOString()};write(KEY,all);delete sec.dataset.edit;url.value='';msg.textContent='✓ iCal salvo somente para esta propriedade/unidade.';render()};
window.addEventListener('stay:scope-change',()=>setTimeout(syncSelection,0));window.addEventListener('storage',e=>{if([SCOPE,PROPS].includes(e.key))setTimeout(syncSelection,0)});syncSelection();render()}
function boot(){const t=setInterval(()=>{if(document.body.classList.contains('ap207-authenticated')){install();if(document.getElementById('icalManager'))clearInterval(t)}},300);setTimeout(()=>clearInterval(t),15000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();