(()=>{'use strict';
let pdfLoading=null,canvasLoading=null;
function loadJsPdf(){if(window.jspdf?.jsPDF)return Promise.resolve(window.jspdf.jsPDF);if(pdfLoading)return pdfLoading;pdfLoading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js';s.onload=()=>window.jspdf?.jsPDF?resolve(window.jspdf.jsPDF):reject(new Error('jsPDF indisponível'));s.onerror=()=>reject(new Error('Falha ao carregar gerador de PDF'));document.head.append(s)});return pdfLoading}
function loadCanvas(){if(window.html2canvas)return Promise.resolve(window.html2canvas);if(canvasLoading)return canvasLoading;canvasLoading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';s.onload=()=>window.html2canvas?resolve(window.html2canvas):reject(new Error('Captura visual indisponível'));s.onerror=()=>reject(new Error('Falha ao carregar captura visual'));document.head.append(s)});return canvasLoading}
function cleanName(v){return String(v||'Stay-in-Control').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'Stay-in-Control'}
function stripControls(root){root.querySelectorAll('button,select,input,form,.page-share-panel,.report-share-panel,.home-share-wrap,.calendar-share-wrap,.reservation-page-toolbar,.expense-page-toolbar,.report-page-toolbar,.no-print').forEach(x=>x.remove());root.querySelectorAll('.reservation-page-hidden,.expense-page-hidden,.report-page-hidden').forEach(x=>x.classList.remove('reservation-page-hidden','expense-page-hidden','report-page-hidden'));return root}
function copyCalendarGrid(source,clone){const sg=source.querySelector?.('#calendarGrid'),cg=clone.querySelector?.('#calendarGrid');if(!sg||!cg)return;cg.innerHTML=sg.innerHTML;cg.className=sg.className;cg.style.cssText=sg.style.cssText;const sourceKids=[...sg.children],cloneKids=[...cg.children];sourceKids.forEach((el,i)=>{if(!cloneKids[i])return;cloneKids[i].className=el.className;cloneKids[i].style.cssText=el.style.cssText;});}
function visualWrapper(page){const wrap=document.createElement('div');wrap.className='stay-pdf-capture';wrap.style.cssText='position:fixed;left:-10000px;top:0;width:760px;box-sizing:border-box;padding:28px;background:#fff;color:#172033;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;z-index:-1;';const head=document.createElement('div');head.style.cssText='margin-bottom:18px;padding-bottom:12px;border-bottom:1px solid #dbe3ee';head.innerHTML=`<div style="font-size:13px;font-weight:800;color:#175cd3;letter-spacing:.03em">STAY IN CONTROL 1.0</div><div style="font-size:22px;font-weight:900;margin-top:5px">${page.title||'Documento'}</div>${page.subtitle?`<div style="font-size:12px;color:#667085;margin-top:4px">${page.subtitle}</div>`:''}`;wrap.append(head);const els=page.elements?.length?page.elements:(page.element?[page.element]:[]);els.forEach(el=>{if(!el)return;const raw=el.cloneNode(true);copyCalendarGrid(el,raw);const clone=stripControls(raw);clone.removeAttribute('hidden');clone.style.display='block';clone.style.maxWidth='100%';clone.style.width='100%';clone.style.boxSizing='border-box';wrap.append(clone)});if(!els.length&&page.text){const pre=document.createElement('div');pre.style.cssText='white-space:pre-wrap;font-size:14px;line-height:1.5';pre.textContent=page.text;wrap.append(pre)}document.body.append(wrap);return wrap}
async function capturePage(page){const html2canvas=await loadCanvas();const wrap=visualWrapper(page);try{await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const canvas=await html2canvas(wrap,{backgroundColor:'#ffffff',scale:2,useCORS:true,allowTaint:false,logging:false,windowWidth:760,scrollX:0,scrollY:0});return canvas}finally{wrap.remove()}}
async function buildPdf(title,pages,filename){const [jsPDF]=await Promise.all([loadJsPdf(),loadCanvas()]);const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});const all=(pages||[]).filter(Boolean);for(let index=0;index<all.length;index++){if(index)doc.addPage();const canvas=await capturePage(all[index]);const img=canvas.toDataURL('image/jpeg',0.93);const pageW=210,pageH=297,margin=8,maxW=pageW-margin*2,maxH=pageH-margin*2;const ratio=Math.min(maxW/canvas.width,maxH/canvas.height);const w=canvas.width*ratio,h=canvas.height*ratio,x=(pageW-w)/2,y=margin;doc.addImage(img,'JPEG',x,y,w,h,undefined,'FAST');doc.setFontSize(7);doc.setTextColor(120);doc.text(`Página ${index+1} de ${all.length}`,pageW-margin,pageH-3,{align:'right'});doc.setTextColor(0)}const blob=doc.output('blob');const name=`${cleanName(filename||title||'Stay-in-Control')}.pdf`;return new File([blob],name,{type:'application/pdf'})}
async function sharePdf({title='Stay in Control 1.0',pages=[],filename='Stay-in-Control'}){if(!pages?.length)throw new Error('Nenhuma página para gerar');const file=await buildPdf(title,pages,filename);try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title,files:[file]});return true}}catch(e){if(e?.name==='AbortError')return false}const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),5000);alert('O PDF visual foi gerado. Abra o arquivo para compartilhar.');return true}
window.StayPdf={buildPdf,sharePdf};
})();