(()=>{'use strict';
const AUTH='ap207-auth-profile-v1';
let page=0,rebuilding=false;
function profile(){try{return JSON.parse(localStorage.getItem(AUTH)||'null')?.profile||{role:'super_admin'}}catch{return{role:'super_admin'}}}
function styles(){if(document.getElementById('reportPagesStyles'))return;const s=document.createElement('style');s.id='reportPagesStyles';s.textContent=`.report-page-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:14px 0 12px;padding:10px 12px;border:1px solid #dbe3ee;border-radius:14px;background:#fff}.report-page-toolbar button{min-height:42px;border:1px solid #dbe3ee;border-radius:11px;background:#fff;padding:0 13px;font-weight:800;color:#172033}.report-page-toolbar button:disabled{opacity:.4}.report-page-label{flex:1;text-align:center}.report-page-label strong{display:block;font-size:.88rem}.report-page-label span{display:block;color:#667085;font-size:.72rem;margin-top:2px}.report-type-field{margin-bottom:12px}.report-type-field select{width:100%}.report-page-hidden{display:none!important}.report-page-title{margin:0 0 12px;padding:10px 12px;border-radius:12px;background:#f8fafc;border:1px solid #e2e8f0}.report-page-title strong{display:block}.report-page-title span{display:block;color:#667085;font-size:.78rem;margin-top:2px}@media(max-width:520px){.report-page-toolbar{position:sticky;bottom:88px;z-index:20;box-shadow:0 8px 24px rgba(15,23,42,.12)}.report-page-toolbar button{min-width:84px;padding:0 9px}.report-page-label strong{font-size:.8rem}.report-page-label span{font-size:.67rem}}`;document.head.append(s)}
function typeControl(section){if(profile().role!=='super_admin')return null;let field=document.getElementById('reportTypeField');if(field)return field.querySelector('select');field=document.createElement('div');field.id='reportTypeField';field.className='field report-type-field';field.innerHTML='<label for="reportTypeSelect">Tipo de relatório</label><select id="reportTypeSelect"><option value="super">Superadministrador</option><option value="admin">Administrador</option></select>';const adminField=section.querySelector('#adminFilterField');if(adminField)adminField.insertAdjacentElement('beforebegin',field);else section.querySelector('.report-filters')?.prepend(field);const sel=field.querySelector('select');sel.addEventListener('change',()=>{const a=section.querySelector('#adminFilterField'),as=section.querySelector('#consolidatedAdmin');if(sel.value==='super'){if(as)as.value='all';if(a)a.hidden=true}else if(a)a.hidden=false;page=0;section.querySelector('#refreshConsolidated')?.click();setTimeout(build,100)});return sel}
function modeSync(section){const sel=typeControl(section),adminField=section.querySelector('#adminFilterField');if(profile().role!=='super_admin')return;if(sel?.value==='super'){if(adminField)adminField.hidden=true}else if(adminField)adminField.hidden=false}
function nodes(section){const toolbar=section.querySelector('.report-toolbar'),note=section.querySelector('.general-report-note'),metrics=section.querySelector(':scope > .report-metrics'),owners=[...(section.querySelector('#ownerTotals')?.children||[])].filter(x=>x.classList.contains('general-owner-card')),units=[...(section.querySelector('#consolidatedRows')?.children||[])].filter(x=>x.classList.contains('consolidated-row')),revenue=section.querySelector('#stayRevenue');return{toolbar,note,metrics,owners,units,revenue}}
function pageData(section){const n=nodes(section),pages=[];pages.push({kind:'summary',title:'Resumo geral',subtitle:'Visão consolidada do período',show:[n.metrics,n.revenue].filter(Boolean)});n.owners.forEach((el,i)=>{const name=el.querySelector('h3')?.textContent?.trim()||`Proprietário ${i+1}`;pages.push({kind:'owner',title:`Proprietário: ${name}`,subtitle:'Resumo individual do proprietário',show:[el]})});n.units.forEach((el,i)=>{const strongs=el.querySelectorAll('strong'),owner=strongs[0]?.textContent?.trim()||'Proprietário',unit=strongs[1]?.textContent?.trim()||`Unidade ${i+1}`;pages.push({kind:'unit',title:`Unidade: ${unit}`,subtitle:`${owner} • detalhamento da unidade`,show:[el]})});return{n,pages}}
function controls(section){let bar=document.getElementById('reportPageToolbar');if(bar)return bar;bar=document.createElement('div');bar.id='reportPageToolbar';bar.className='report-page-toolbar';bar.innerHTML='<button type="button" data-prev>← Voltar</button><div class="report-page-label"><strong id="reportPageCount">Página 1</strong><span id="reportPageName">Resumo geral</span></div><button type="button" data-next>Próximo →</button>';const note=section.querySelector('.general-report-note');(note||section.querySelector('.report-metrics'))?.insertAdjacentElement('afterend',bar);bar.querySelector('[data-prev]').onclick=()=>{if(page>0){page--;renderPage(section);window.scrollTo({top:section.offsetTop-12,behavior:'smooth'})}};bar.querySelector('[data-next]').onclick=()=>{const total=pageData(section).pages.length;if(page<total-1){page++;renderPage(section);window.scrollTo({top:section.offsetTop-12,behavior:'smooth'})}};return bar}
function titleBox(section){let b=document.getElementById('reportPageTitle');if(b)return b;b=document.createElement('div');b.id='reportPageTitle';b.className='report-page-title';controls(section).insertAdjacentElement('afterend',b);return b}
function renderPage(section){if(rebuilding)return;const{n,pages}=pageData(section);if(!pages.length)return;page=Math.max(0,Math.min(page,pages.length-1));const current=pages[page];[n.metrics,n.revenue,...n.owners,...n.units].filter(Boolean).forEach(el=>el.classList.add('report-page-hidden'));current.show.forEach(el=>el?.classList.remove('report-page-hidden'));const bar=controls(section);bar.querySelector('[data-prev]').disabled=page===0;bar.querySelector('[data-next]').disabled=page===pages.length-1;bar.querySelector('#reportPageCount').textContent=`Página ${page+1} de ${pages.length}`;bar.querySelector('#reportPageName').textContent=current.title;const b=titleBox(section);b.innerHTML=`<strong>${current.title}</strong><span>${current.subtitle}</span>`;modeSync(section)}
function build(){const section=document.getElementById('consolidatedReports');if(!section)return;styles();typeControl(section);controls(section);renderPage(section)}
function boot(){const wait=setInterval(()=>{const section=document.getElementById('consolidatedReports');if(!section)return;clearInterval(wait);build();const owners=section.querySelector('#ownerTotals'),rows=section.querySelector('#consolidatedRows');const observer=new MutationObserver(()=>{if(rebuilding)return;rebuilding=true;setTimeout(()=>{rebuilding=false;page=0;renderPage(section)},40)});if(owners)observer.observe(owners,{childList:true});if(rows)observer.observe(rows,{childList:true});section.querySelector('#refreshConsolidated')?.addEventListener('click',()=>{page=0;setTimeout(()=>renderPage(section),80)},true);document.querySelector('[data-screen="reports"]')?.addEventListener('click',()=>setTimeout(build,120))},250);setTimeout(()=>clearInterval(wait),10000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();