(()=>{'use strict';
const AUTH='ap207-auth-profile-v1',PROPS='ap207-dashboard-properties-v1',EXP='ap207-dashboard-expenses-v1';
const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'});
let page=0,rebuilding=false,focused=false;
function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}}
function profile(){return read(AUTH,{profile:{role:'super_admin'}})?.profile||{role:'super_admin'}}
function styles(){if(document.getElementById('reportPagesStyles'))return;const s=document.createElement('style');s.id='reportPagesStyles';s.textContent=`
.report-page-toolbar{display:grid;grid-template-columns:auto 1fr auto;grid-template-areas:'prev label next';align-items:center;gap:10px;margin:14px 0 12px;padding:10px 12px;border:1px solid #dbe3ee;border-radius:14px;background:#fff}.report-page-toolbar button{min-height:42px;border:1px solid #dbe3ee;border-radius:11px;background:#fff;padding:0 13px;font-weight:800;color:#172033}.report-page-toolbar button:disabled{opacity:.4}.report-page-toolbar [data-prev]{grid-area:prev}.report-page-toolbar [data-next]{grid-area:next}.report-page-label{grid-area:label;text-align:center}.report-page-label strong{display:block;font-size:.88rem}.report-page-label span{display:block;color:#667085;font-size:.72rem;margin-top:2px}.report-type-field{margin-bottom:12px}.report-type-field select{width:100%}.report-page-hidden{display:none!important}.report-page-title{margin:0 0 12px;padding:10px 12px;border-radius:12px;background:#f8fafc;border:1px solid #e2e8f0}.report-page-title strong{display:block}.report-page-title span{display:block;color:#667085;font-size:.78rem;margin-top:2px}.report-close-button{display:none!important}.report-expense-breakdown{margin:14px 0 4px;padding:14px;border:1px solid #e2e8f0;border-radius:14px;background:#fff}.report-expense-breakdown h3{margin:0 0 8px;font-size:1rem}.report-expense-breakdown p{margin:0;color:#667085;font-size:.8rem}.report-expense-row{display:grid;grid-template-columns:1fr auto;gap:10px;padding:10px 0;border-top:1px solid #eef2f6}.report-expense-row:first-of-type{border-top:0}.report-expense-row b{display:block;font-size:.86rem}.report-expense-row small{display:block;color:#667085;margin-top:2px}.report-expense-row strong{color:#b42318;white-space:nowrap}
body.report-pages-focus{overflow:hidden!important}.report-pages-focus .app-nav,.report-pages-focus .scenic-banner,.report-pages-focus .page-header,.report-pages-focus #appStatus,.report-pages-focus #propertySettings,.report-pages-focus [data-screen-panel]:not([data-screen-panel="reports"]),.report-pages-focus #monthlyReport{display:none!important}.report-pages-focus [data-screen-panel="reports"]{display:block!important;position:fixed!important;inset:0!important;z-index:9999!important;overflow-y:auto!important;background:#f5f8fc!important;padding:0 14px 24px!important}.report-pages-focus #consolidatedReports{display:block!important;margin:0 auto!important;max-width:760px!important;min-height:100%!important;border:0!important;border-radius:0!important;box-shadow:none!important;background:#fff!important;padding:0 18px 28px!important}.report-pages-focus #consolidatedReports>.report-toolbar,.report-pages-focus #consolidatedReports>.general-report-note{display:none!important}.report-pages-focus .report-page-toolbar{position:sticky!important;top:0!important;z-index:40!important;margin:0 -18px 14px!important;padding:10px 14px 12px!important;border-width:0 0 1px!important;border-radius:0!important;box-shadow:0 7px 20px rgba(15,23,42,.08)!important;grid-template-columns:auto 1fr auto!important;grid-template-areas:'close close close' 'prev label next'!important}.report-pages-focus .report-close-button{grid-area:close!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;width:100%!important;min-height:44px!important;border:0!important;background:#dc2626!important;color:#fff!important;font-size:.9rem!important}.report-pages-focus .report-page-title{margin-top:0!important;padding:12px 14px!important}.report-pages-focus #stayRevenue{margin-top:12px!important}
@media(max-width:520px){.report-page-toolbar button{min-width:82px;padding:0 8px}.report-page-label strong{font-size:.82rem}.report-page-label span{font-size:.68rem}.report-pages-focus [data-screen-panel="reports"]{padding:0!important}.report-pages-focus #consolidatedReports{padding:0 14px 22px!important}.report-pages-focus .report-page-toolbar{margin:0 -14px 12px!important;padding:9px 10px 11px!important;gap:8px!important}.report-pages-focus .report-close-button{min-height:42px!important}.report-pages-focus .report-page-toolbar [data-prev],.report-pages-focus .report-page-toolbar [data-next]{min-width:86px!important}.report-pages-focus .report-page-label strong{font-size:.84rem!important}.report-pages-focus .report-page-label span{font-size:.68rem!important}}
`;document.head.append(s)}
function typeControl(section){if(profile().role!=='super_admin')return null;let field=document.getElementById('reportTypeField');if(field)return field.querySelector('select');field=document.createElement('div');field.id='reportTypeField';field.className='field report-type-field';field.innerHTML='<label for="reportTypeSelect">Tipo de relatório</label><select id="reportTypeSelect"><option value="super">Superadministrador</option><option value="admin">Administrador</option></select>';const adminField=section.querySelector('#adminFilterField');if(adminField)adminField.insertAdjacentElement('beforebegin',field);else section.querySelector('.report-filters')?.prepend(field);const sel=field.querySelector('select');sel.addEventListener('change',()=>{const a=section.querySelector('#adminFilterField'),as=section.querySelector('#consolidatedAdmin');if(sel.value==='super'){if(as)as.value='all';if(a)a.hidden=true}else if(a)a.hidden=false;page=0;section.querySelector('#refreshConsolidated')?.click();setTimeout(build,100)});return sel}
function modeSync(section){const sel=typeControl(section),adminField=section.querySelector('#adminFilterField');if(profile().role!=='super_admin')return;if(sel?.value==='super'){if(adminField)adminField.hidden=true}else if(adminField)adminField.hidden=false}
function nodes(section){const metrics=section.querySelector(':scope > .report-metrics'),owners=[...(section.querySelector('#ownerTotals')?.children||[])].filter(x=>x.classList.contains('general-owner-card')),units=[...(section.querySelector('#consolidatedRows')?.children||[])].filter(x=>x.classList.contains('consolidated-row')),revenue=section.querySelector('#stayRevenue');return{metrics,owners,units,revenue}}
function pageData(section){const n=nodes(section),pages=[];pages.push({kind:'summary',title:'Resumo geral',subtitle:'Visão consolidada do período',show:[n.metrics,n.revenue].filter(Boolean)});n.owners.forEach((el,i)=>{const name=el.querySelector('h3')?.textContent?.trim()||`Proprietário ${i+1}`;pages.push({kind:'owner',owner:name,title:`Proprietário: ${name}`,subtitle:'Resumo individual do proprietário',show:[el]})});n.units.forEach((el,i)=>{const strongs=el.querySelectorAll('strong'),owner=strongs[0]?.textContent?.trim()||'Proprietário',unit=strongs[1]?.textContent?.trim()||`Unidade ${i+1}`;pages.push({kind:'unit',owner,unit,title:`Unidade: ${unit}`,subtitle:`${owner} • detalhamento da unidade`,show:[el]})});return{n,pages}}
function properties(){const p=read(PROPS,{properties:[]});return Array.isArray(p?.properties)?p.properties:[]}
function visiblePropertyMatches(section){const ps=properties(),rows=[...(section.querySelector('#consolidatedRows')?.children||[])].filter(x=>x.classList.contains('consolidated-row'));return rows.map(el=>{const s=el.querySelectorAll('strong'),owner=s[0]?.textContent?.trim()||'',unit=s[1]?.textContent?.trim()||'';const p=ps.find(x=>String(x.ownerName||'').trim()===owner&&(String(x.unit||'').trim()===unit||String(x.name||'').trim()===unit));return p||null}).filter(Boolean)}
function expensesFor(p,year,month){let data=read(`${EXP}:${p.id}`,null);if(!Array.isArray(data?.expenses)&&`${p.id||''} ${p.unit||''}`.toLowerCase().includes('207'))data=read(EXP,null);const prefix=`${year}-${String(month).padStart(2,'0')}`;return Array.isArray(data?.expenses)?data.expenses.filter(e=>String(e.date||'').startsWith(prefix)):[]}
function expenseBox(section,current){let box=document.getElementById('reportPageExpenses');if(!box){box=document.createElement('section');box.id='reportPageExpenses';box.className='report-expense-breakdown';titleBox(section).insertAdjacentElement('afterend',box)}const year=Number(section.querySelector('#consolidatedYear')?.value)||new Date().getFullYear(),month=Number(section.querySelector('#consolidatedMonth')?.value)||new Date().getMonth()+1;let ps=visiblePropertyMatches(section);if(current.kind==='owner')ps=ps.filter(p=>String(p.ownerName||'').trim()===current.owner);if(current.kind==='unit')ps=ps.filter(p=>String(p.ownerName||'').trim()===current.owner&&(String(p.unit||'').trim()===current.unit||String(p.name||'').trim()===current.unit));const items=[];ps.forEach(p=>expensesFor(p,year,month).forEach(e=>items.push({p,e})));if(!items.length){box.innerHTML='<h3>Despesas do período</h3><p>Nenhuma despesa lançada nesta página para o período selecionado.</p>';return}box.innerHTML='<h3>Despesas que compõem o total</h3>';items.forEach(({p,e})=>{const row=document.createElement('div');row.className='report-expense-row';const left=document.createElement('div'),title=document.createElement('b'),small=document.createElement('small'),value=document.createElement('strong');title.textContent=e.category||'Despesa';small.textContent=`${p.unit||p.name||'Unidade'}${e.description?` • ${e.description}`:''}`;value.textContent=`− ${money.format(Number(e.value)||0)}`;left.append(title,small);row.append(left,value);box.append(row)})}
function exitFocus(section){focused=false;document.body.classList.remove('report-pages-focus');window.scrollTo({top:section.offsetTop-12,behavior:'smooth'})}
function enterFocus(section){focused=true;document.body.classList.add('report-pages-focus');section.closest('[data-screen-panel="reports"]')?.scrollTo?.({top:0});setTimeout(()=>section.closest('[data-screen-panel="reports"]')?.scrollTo?.({top:0}),30)}
function controls(section){let bar=document.getElementById('reportPageToolbar');if(bar)return bar;bar=document.createElement('div');bar.id='reportPageToolbar';bar.className='report-page-toolbar';bar.innerHTML='<button type="button" class="report-close-button" data-close aria-label="Sair do relatório">← Sair do relatório</button><button type="button" data-prev>← Voltar</button><div class="report-page-label"><strong id="reportPageCount">Página 1</strong><span id="reportPageName">Resumo geral</span></div><button type="button" data-next>Próximo →</button>';const note=section.querySelector('.general-report-note');(note||section.querySelector('.report-metrics'))?.insertAdjacentElement('afterend',bar);bar.querySelector('[data-close]').onclick=()=>exitFocus(section);bar.querySelector('[data-prev]').onclick=()=>{if(page>0){page--;renderPage(section);section.closest('[data-screen-panel="reports"]')?.scrollTo({top:0,behavior:'smooth'})}};bar.querySelector('[data-next]').onclick=()=>{const total=pageData(section).pages.length;if(page<total-1){page++;renderPage(section);section.closest('[data-screen-panel="reports"]')?.scrollTo({top:0,behavior:'smooth'})}};return bar}
function titleBox(section){let b=document.getElementById('reportPageTitle');if(b)return b;b=document.createElement('div');b.id='reportPageTitle';b.className='report-page-title';controls(section).insertAdjacentElement('afterend',b);return b}
function renderPage(section){if(rebuilding)return;const{n,pages}=pageData(section);if(!pages.length)return;page=Math.max(0,Math.min(page,pages.length-1));const current=pages[page];[n.metrics,n.revenue,...n.owners,...n.units].filter(Boolean).forEach(el=>el.classList.add('report-page-hidden'));current.show.forEach(el=>el?.classList.remove('report-page-hidden'));const bar=controls(section);bar.querySelector('[data-prev]').disabled=page===0;bar.querySelector('[data-next]').disabled=page===pages.length-1;bar.querySelector('#reportPageCount').textContent=`Página ${page+1} de ${pages.length}`;bar.querySelector('#reportPageName').textContent=current.title;const b=titleBox(section);b.innerHTML=`<strong>${current.title}</strong><span>${current.subtitle}</span>`;expenseBox(section,current);modeSync(section)}
function build(){const section=document.getElementById('consolidatedReports');if(!section)return;styles();typeControl(section);controls(section);renderPage(section)}
function boot(){const wait=setInterval(()=>{const section=document.getElementById('consolidatedReports');if(!section)return;clearInterval(wait);build();const owners=section.querySelector('#ownerTotals'),rows=section.querySelector('#consolidatedRows');const observer=new MutationObserver(()=>{if(rebuilding)return;rebuilding=true;setTimeout(()=>{rebuilding=false;page=0;renderPage(section)},40)});if(owners)observer.observe(owners,{childList:true});if(rows)observer.observe(rows,{childList:true});section.querySelector('#refreshConsolidated')?.addEventListener('click',()=>{page=0;setTimeout(()=>{renderPage(section);enterFocus(section)},100)},false);document.querySelector('[data-screen="reports"]')?.addEventListener('click',()=>{if(focused)exitFocus(section);setTimeout(build,120)})},250);setTimeout(()=>clearInterval(wait),10000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();