(()=>{'use strict';
let page=0,rendering=false;
function styles(){if(document.getElementById('reservationPagesStyles'))return;const s=document.createElement('style');s.id='reservationPagesStyles';s.textContent=`.reservation-page-toolbar{display:grid;grid-template-columns:auto 1fr auto;grid-template-areas:'prev label next' 'share share share';align-items:center;gap:8px;margin:14px 0 10px;padding:9px 10px;border:1px solid #dbe3ee;border-radius:14px;background:#fff}.reservation-page-toolbar button{min-height:40px;border:1px solid #dbe3ee;border-radius:10px;background:#fff;padding:0 10px;font-weight:800;color:#172033}.reservation-page-toolbar button:disabled{opacity:.38}.reservation-page-toolbar [data-prev]{grid-area:prev}.reservation-page-toolbar [data-next]{grid-area:next}.reservation-page-label{grid-area:label;text-align:center}.reservation-page-label strong{display:block;font-size:.86rem}.reservation-page-label span{display:block;margin-top:2px;color:#667085;font-size:.68rem}.reservation-page-share{grid-area:share!important;justify-self:center!important;min-height:32px!important;padding:0 12px!important;border:0!important;background:#eff6ff!important;color:#175cd3!important;font-size:.72rem!important}.reservation-page-hidden{display:none!important}.page-share-panel{display:none;margin:8px 0 12px;padding:12px;border:1px solid #bfdbfe;border-radius:13px;background:#eff6ff}.page-share-panel.open{display:block}.page-share-panel h4{margin:0 0 8px}.page-share-options{display:grid;gap:7px}.page-share-option{display:flex;align-items:center;gap:9px;padding:7px 8px;border-radius:10px;background:#fff}.page-share-option input{appearance:none;width:20px;height:20px;border:2px solid #2563eb;border-radius:50%;margin:0;display:grid;place-content:center}.page-share-option input:checked:after{content:'';width:10px;height:10px;border-radius:50%;background:#2563eb}.page-share-actions{display:flex;gap:8px;margin-top:10px}.page-share-actions button{flex:1;min-height:38px;border-radius:10px;border:0;font-weight:800}.page-share-confirm{background:#2563eb!important;color:#fff!important}.page-share-cancel{background:#fff!important;color:#334155!important;border:1px solid #dbe3ee!important}@media(max-width:520px){.reservation-page-toolbar{gap:7px;padding:8px}.reservation-page-toolbar button{min-width:82px;padding:0 7px}.reservation-page-label strong{font-size:.8rem}.reservation-page-label span{font-size:.64rem}}`;document.head.append(s)}
function container(){return document.getElementById('reservations')}
function items(){const c=container();return c?[...c.children].filter(el=>el.nodeType===1):[]}
function guestLabel(el,index){const txt=el?.innerText||'';const line=txt.split('\n').map(x=>x.trim()).find(Boolean);return line||`Reserva ${index+1}`}
function pageText(el,index){return `Stay in Control 1.0\nReserva — Página ${index+1}\n${guestLabel(el,index)}\n\n${(el.innerText||'').trim()}`}
function sharePanel(){let p=document.getElementById('reservationSharePanel');if(p)return p;const b=toolbar();if(!b)return null;p=document.createElement('div');p.id='reservationSharePanel';p.className='page-share-panel';b.insertAdjacentElement('afterend',p);return p}
function openShare(){const p=sharePanel(),list=items();if(!p||!list.length)return;p.innerHTML='<h4>Selecionar páginas para compartilhar</h4><div class="page-share-options"></div><div class="page-share-actions"><button type="button" class="page-share-cancel">Cancelar</button><button type="button" class="page-share-confirm">Compartilhar</button></div>';const o=p.querySelector('.page-share-options');const all=document.createElement('label');all.className='page-share-option';all.innerHTML='<input type="checkbox" data-all><span>Todas as páginas</span>';o.append(all);list.forEach((el,i)=>{const l=document.createElement('label');l.className='page-share-option';l.innerHTML=`<input type="checkbox" data-page="${i}" ${i===page?'checked':''}><span>Página ${i+1} — ${guestLabel(el,i)}</span>`;o.append(l)});const allInput=all.querySelector('input');allInput.onchange=()=>o.querySelectorAll('[data-page]').forEach(x=>x.checked=allInput.checked);p.querySelector('.page-share-cancel').onclick=()=>p.classList.remove('open');p.querySelector('.page-share-confirm').onclick=async()=>{const selected=[...o.querySelectorAll('[data-page]:checked')].map(x=>Number(x.dataset.page));if(!selected.length){alert('Selecione pelo menos uma página.');return}const text=selected.map(i=>pageText(list[i],i)).join('\n\n────────────\n\n');try{if(navigator.share)await navigator.share({title:'Reservas - Stay in Control 1.0',text});else if(navigator.clipboard){await navigator.clipboard.writeText(text);alert('Páginas copiadas para compartilhar.')}else alert(text)}catch(e){if(e?.name!=='AbortError')alert('Não foi possível compartilhar agora.')}};p.classList.add('open')}
function toolbar(){let b=document.getElementById('reservationPageToolbar');if(b)return b;const c=container();if(!c)return null;b=document.createElement('div');b.id='reservationPageToolbar';b.className='reservation-page-toolbar';b.innerHTML='<button type="button" data-prev>← Voltar</button><div class="reservation-page-label"><strong id="reservationPageCount">Página 1</strong><span id="reservationPageName">Reserva</span></div><button type="button" data-next>Próximo →</button><button type="button" class="reservation-page-share" data-share>↗ Compartilhar</button>';c.insertAdjacentElement('beforebegin',b);b.querySelector('[data-prev]').onclick=()=>{if(page>0){page--;render();scrollTop()}};b.querySelector('[data-next]').onclick=()=>{const total=items().length;if(page<total-1){page++;render();scrollTop()}};b.querySelector('[data-share]').onclick=openShare;return b}
function scrollTop(){document.querySelector('[data-screen-panel="reservations"]')?.scrollIntoView({behavior:'smooth',block:'start'})}
function render(){if(rendering)return;rendering=true;requestAnimationFrame(()=>{const list=items(),b=toolbar();if(!b){rendering=false;return}if(!list.length){b.style.display='none';rendering=false;return}b.style.display='grid';page=Math.max(0,Math.min(page,list.length-1));list.forEach((el,i)=>el.classList.toggle('reservation-page-hidden',i!==page));b.querySelector('[data-prev]').disabled=page===0;b.querySelector('[data-next]').disabled=page===list.length-1;b.querySelector('#reservationPageCount').textContent=`Página ${page+1} de ${list.length}`;b.querySelector('#reservationPageName').textContent=guestLabel(list[page],page);document.getElementById('reservationSharePanel')?.classList.remove('open');rendering=false})}
function refresh(reset=false){if(reset)page=0;setTimeout(render,50)}
function boot(){styles();toolbar();render();const c=container();if(c)new MutationObserver(()=>refresh(false)).observe(c,{childList:true,subtree:false});document.querySelector('[data-screen="reservations"]')?.addEventListener('click',()=>refresh(false));document.getElementById('newReservationButton')?.addEventListener('click',()=>{items().forEach(el=>el.classList.remove('reservation-page-hidden'));const b=toolbar();if(b)b.style.display='none';document.getElementById('reservationSharePanel')?.classList.remove('open')});document.getElementById('cancelEditButton')?.addEventListener('click',()=>refresh(false));document.getElementById('reservationForm')?.addEventListener('submit',()=>refresh(true));document.getElementById('propertySelector')?.addEventListener('change',()=>refresh(true))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1350),{once:true});else setTimeout(boot,1350);
})();