(()=>{'use strict';
const AUTH_KEY='ap207-auth-profile-v1';
const INVITES_KEY='stay-control-invitations-v1';
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
const auth=()=>read(AUTH_KEY,null);
const isSuperAdmin=()=>auth()?.profile?.role==='super_admin';
function styles(){if(document.getElementById('stayRoleManagerStyles'))return;const s=document.createElement('style');s.id='stayRoleManagerStyles';s.textContent=`.stay-role-manager{margin-top:18px}.stay-role-list{display:grid;gap:10px;margin-top:14px}.stay-role-row{padding:14px;border:1px solid #e2e8f0;border-radius:14px;background:#fff;display:grid;gap:10px}.stay-role-row strong{display:block}.stay-role-row small{color:#64748b}.stay-role-controls{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.stay-role-controls select{min-height:46px;border:1px solid #d7dee8;border-radius:12px;padding:0 12px;background:#fff;font-size:15px}.stay-role-save{min-height:46px;border:0;border-radius:12px;background:#2563eb;color:#fff;font-weight:800;padding:0 16px}.stay-role-message{margin:10px 0 0;font-weight:700}.stay-role-message.ok{color:#166534}.stay-role-message.err{color:#b42318}@media(max-width:620px){.stay-role-controls{grid-template-columns:1fr}.stay-role-save{width:100%}}`;document.head.append(s)}
function saveInviteRole(email,newRole){const all=read(INVITES_KEY,[]);let changed=false;all.forEach(i=>{if(String(i.email||'').toLowerCase()===email.toLowerCase()){i.role=newRole;changed=true}});if(changed)localStorage.setItem(INVITES_KEY,JSON.stringify(all));}
async function updateRole(email,newRole,button,message){const client=window.AP207Supabase;if(!client){message.className='stay-role-message err';message.textContent='O serviço de acesso ainda está carregando.';return}button.disabled=true;const old=button.textContent;button.textContent='Salvando…';message.textContent='';try{
  const normalized=String(email||'').trim().toLowerCase();
  const {data,error}=await client.from('profiles').update({role:newRole}).eq('email',normalized).select('id,email,role');
  if(error)throw error;
  const rows=Array.isArray(data)?data:[];
  if(!rows.length)throw new Error('Usuário não encontrado.');
  saveInviteRole(normalized,newRole);
  message.className='stay-role-message ok';
  message.textContent=`✅ ${normalized} agora é ${newRole==='admin'?'Administrador':'Proprietário'}. Função atualizada. A pessoa deve tocar em atualizar ou sair e entrar novamente.`;
  button.textContent='Salvo ✓';
  setTimeout(()=>{button.textContent='Salvar função';button.disabled=false},1400);
}catch(err){message.className='stay-role-message err';message.textContent=`❌ Não foi possível trocar a função: ${err?.message||'erro desconhecido'}`;button.disabled=false;button.textContent=old}}
async function loadProfiles(){const client=window.AP207Supabase;if(!client)return[];const {data,error}=await client.from('profiles').select('id,email,name,role,active').neq('role','super_admin').order('name',{ascending:true});if(error)throw error;const seen=new Map();(data||[]).forEach(p=>{const key=String(p.email||p.id||'').toLowerCase();if(!seen.has(key)||p.role==='admin')seen.set(key,p)});return[...seen.values()]}
function currentScreen(){const active=document.querySelector('.nav-item.active[data-screen]');if(active)return active.dataset.screen;const visible=[...document.querySelectorAll('[data-screen-panel]')].find(el=>!el.hidden);return visible?.dataset.screenPanel||'home';}
function syncVisibility(){const section=document.getElementById('stayRoleManager');if(!section)return;section.hidden=currentScreen()!=='home';}
function bindScreenVisibility(){if(document.body.dataset.stayRoleVisibilityBound==='1')return;document.body.dataset.stayRoleVisibilityBound='1';document.querySelectorAll('[data-screen]').forEach(btn=>btn.addEventListener('click',()=>setTimeout(syncVisibility,0)));const observer=new MutationObserver(syncVisibility);document.querySelectorAll('[data-screen-panel],.nav-item[data-screen]').forEach(el=>observer.observe(el,{attributes:true,attributeFilter:['hidden','class']}));}
function install(){if(!isSuperAdmin()||document.getElementById('stayRoleManager'))return false;const anchor=document.getElementById('stayUserSection');if(!anchor)return false;styles();const section=document.createElement('section');section.id='stayRoleManager';section.className='panel stay-role-manager';section.innerHTML=`<div class="panel-heading"><div><p class="eyebrow">Super Administrador</p><h2>Tipo de acesso dos usuários</h2></div></div><p>Somente o Super Administrador pode trocar uma pessoa entre Proprietário e Administrador.</p><div id="stayRoleList" class="stay-role-list"><small>Carregando usuários…</small></div><p id="stayRoleMessage" class="stay-role-message" aria-live="polite"></p>`;anchor.insertAdjacentElement('afterend',section);const list=section.querySelector('#stayRoleList'),message=section.querySelector('#stayRoleMessage');loadProfiles().then(profiles=>{list.replaceChildren();if(!profiles.length){list.innerHTML='<small>Nenhum usuário disponível.</small>';return}profiles.forEach(p=>{const row=document.createElement('div');row.className='stay-role-row';const info=document.createElement('div');info.innerHTML=`<strong>${p.name||p.email}</strong><small>${p.email}</small>`;const controls=document.createElement('div');controls.className='stay-role-controls';const select=document.createElement('select');select.innerHTML='<option value="owner">Proprietário</option><option value="admin">Administrador</option>';select.value=p.role==='admin'?'admin':'owner';const save=document.createElement('button');save.type='button';save.className='stay-role-save';save.textContent='Salvar função';save.addEventListener('click',()=>updateRole(p.email,select.value,save,message));controls.append(select,save);row.append(info,controls);list.append(row)})}).catch(err=>{list.innerHTML=`<small style="color:#b42318">Não foi possível carregar os usuários: ${err?.message||''}</small>`});bindScreenVisibility();syncVisibility();return true}
function boot(){let tries=0;const t=setInterval(()=>{tries++;if(install()||tries>120)clearInterval(t)},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();