(()=>{'use strict';
const HTML2CANVAS='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';
const active=()=>document.querySelector('.app-screen:not([hidden])')?.dataset.screenPanel||'home';
function loadCanvas(){if(window.html2canvas)return Promise.resolve(window.html2canvas);return new Promise((ok,fail)=>{let s=document.querySelector('script[data-stay-card-canvas]');if(!s){s=document.createElement('script');s.src=HTML2CANVAS;s.async=true;s.dataset.stayCardCanvas='1';document.head.appendChild(s)}s.addEventListener('load',()=>ok(window.html2canvas),{once:true});s.addEventListener('error',()=>fail(new Error('Não foi possível preparar a imagem.')),{once:true})})}
function styles(){if(document.getElementById('stayShareCardCss'))return;const s=document.createElement('style');s.id='stayShareCardCss';s.textContent=`.stay-share-modal{position:fixed;inset:0;z-index:100500;background:rgba(15,23,42,.55);display:flex;align-items:center;justify-content:center;padding:20px}.stay-share-dialog{width:min(520px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:20px;box-shadow:0 24px 70px rgba(15,23,42,.28);padding:18px}.stay-share-head{display:flex;align-items:center;gap:12px;margin-bottom:14px}.stay-share-head h3{margin:0;flex:1;font-size:20px}.stay-share-close{border:0;background:#eef2f7;border-radius:50%;width:38px;height:38px;font-size:20px}.stay-res-card{width:100%;box-sizing:border-box;border:1px solid #dbe2ea;border-radius:18px;background:#f8fafc;padding:20px;color:#172033}.stay-res-brand{font-size:13px;font-weight:900;letter-spacing:.08em;color:#4f46e5}.stay-res-status{display:inline-block;margin-top:12px;padding:6px 10px;border-radius:999px;background:#dcfce7;color:#166534;font-size:12px;font-weight:900}.stay-res-title{font-size:22px;font-weight:900;margin:12px 0 16px}.stay-res-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.stay-res-item{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:11px}.stay-res-item small{display:block;color:#667085;margin-bottom:4px}.stay-res-item strong{display:block;word-break:break-word}.stay-res-foot{margin-top:14px;padding-top:12px;border-top:1px solid #e5e7eb;color:#667085;font-size:12px}.stay-share-actions{display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-top:14px}.stay-share-actions button{border:0;border-radius:12px;padding:11px 8px;font-weight:850;background:#e8eef8;color:#172033}.stay-share-actions .primary{background:#4f46e5;color:#fff}.stay-share-note{font-size:12px;color:#667085;margin:10px 2px 0}@media(max-width:600px){.stay-share-modal{padding:10px;align-items:flex-end}.stay-share-dialog{border-radius:20px 20px 12px 12px;max-height:94vh}.stay-res-card{padding:16px}.stay-res-grid{grid-template-columns:1fr 1fr}.stay-share-actions{grid-template-columns:1fr}.stay-share-note{text-align:center}}` ;document.head.appendChild(s)}
const text=(el,sel)=>el?.querySelector(sel)?.textContent?.trim()||'';
function pair(card,label){const all=[...card.querySelectorAll('*')];const node=all.find(x=>x.children.length===0&&x.textContent.trim().toLowerCase().includes(label.toLowerCase()));if(!node)return'';const p=node.parentElement;return p?.querySelector('strong,dd,span:last-child')?.textContent?.trim()||node.nextElementSibling?.textContent?.trim()||''}
function reservationData(card){const raw=card?.innerText||'';const lines=raw.split('\n').map(x=>x.trim()).filter(Boolean);const status=lines.find(x=>/confirmada|estimada|pendente|cancelada/i.test(x))||'Reserva';const guest=pair(card,'hóspede')||lines.find(x=>!/^reserva|confirmada|estimada|pendente|cancelada|editar|excluir/i.test(x))||'—';const platform=pair(card,'plataforma')||lines.find(x=>/airbnb|booking|vrbo|direto/i.test(x))||'—';const checkIn=pair(card,'check-in')||pair(card,'entrada')||'—';const checkOut=pair(card,'check-out')||pair(card,'saída')||'—';const nights=pair(card,'noites')||'—';const property=document.getElementById('propertyName')?.textContent?.trim()||'Propriedade';return{status,guest,platform,checkIn,checkOut,nights,property}}
function makeCard(d){const c=document.createElement('div');c.className='stay-res-card';const esc=v=>String(v||'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));c.innerHTML=`<div class="stay-res-brand">STAY IN CONTROL 1.0</div><span class="stay-res-status">${esc(d.status)}</span><div class="stay-res-title">${esc(d.property)}</div><div class="stay-res-grid"><div class="stay-res-item"><small>Hóspede</small><strong>${esc(d.guest)}</strong></div><div class="stay-res-item"><small>Plataforma</small><strong>${esc(d.platform)}</strong></div><div class="stay-res-item"><small>Check-in</small><strong>${esc(d.checkIn)}</strong></div><div class="stay-res-item"><small>Check-out</small><strong>${esc(d.checkOut)}</strong></div><div class="stay-res-item"><small>Noites</small><strong>${esc(d.nights)}</strong></div><div class="stay-res-item"><small>Status</small><strong>${esc(d.status)}</strong></div></div><div class="stay-res-foot">Informações compartilhadas pelo Stay in Control.</div>`;return c}
async function pngFile(card){const h2c=await loadCanvas(),canvas=await h2c(card,{backgroundColor:'#f8fafc',scale:2,logging:false,useCORS:true});const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));return new File([blob],'Stay-in-Control-reserva.png',{type:'image/png'})}
async function nativeShare(file){const payload={title:'Reserva - Stay in Control 1.0',text:'Informações da reserva',files:[file]};if(navigator.share&&(!navigator.canShare||navigator.canShare(payload)))return navigator.share(payload);throw new Error('native-unavailable')}
function download(file){const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2500)}
async function copy(file){if(navigator.clipboard&&window.ClipboardItem){await navigator.clipboard.write([new ClipboardItem({'image/png':file})]);return}throw new Error('copy-unavailable')}
function modal(card){styles();document.querySelector('.stay-share-modal')?.remove();const d=reservationData(card),m=document.createElement('div');m.className='stay-share-modal';const box=document.createElement('div');box.className='stay-share-dialog';box.innerHTML='<div class="stay-share-head"><h3>Compartilhar reserva</h3><button class="stay-share-close" type="button" aria-label="Fechar">×</button></div>';const preview=makeCard(d),actions=document.createElement('div');actions.className='stay-share-actions';actions.innerHTML='<button class="primary" type="button" data-share>Compartilhar</button><button type="button" data-download>Baixar imagem</button><button type="button" data-copy>Copiar imagem</button>';const note=document.createElement('p');note.className='stay-share-note';note.textContent=matchMedia('(max-width: 600px)').matches?'No celular, Compartilhar abre as opções do aparelho.':'No computador, você também pode baixar ou copiar a imagem para WhatsApp Web, e-mail e mensagens.';box.append(preview,actions,note);m.append(box);document.body.append(m);const close=()=>m.remove();box.querySelector('.stay-share-close').onclick=close;m.onclick=e=>{if(e.target===m)close()};actions.querySelector('[data-share]').onclick=async()=>{try{await nativeShare(await pngFile(preview))}catch(e){if(e?.name==='AbortError')return;download(await pngFile(preview))}};actions.querySelector('[data-download]').onclick=async()=>download(await pngFile(preview));actions.querySelector('[data-copy]').onclick=async()=>{try{await copy(await pngFile(preview));note.textContent='Imagem copiada. Agora é só colar onde quiser.'}catch{note.textContent='Este navegador não permite copiar a imagem. Use “Baixar imagem”.'}}}
function nearestCard(button){return button.closest('.booking,.reservation-card')||document.querySelector('#reservations .booking,#reservations .reservation-card')}
function installReservationButtons(){document.querySelectorAll('#reservations .booking,#reservations .reservation-card').forEach(card=>{let actions=card.querySelector('.booking-actions,.actions');if(!actions)return;if(actions.querySelector('.stay-res-share'))return;const b=document.createElement('button');b.type='button';b.className='button button-secondary stay-res-share';b.textContent='↗ Compartilhar';b.onclick=e=>{e.preventDefault();e.stopPropagation();modal(card)};const del=actions.querySelector('[data-action="delete"],.delete');del?actions.insertBefore(b,del):actions.append(b)})}
function interceptTop(){document.querySelectorAll('.app-screen[data-screen-panel="reservations"] > .stay-share-pages,#shareReservations').forEach(b=>{if(b.dataset.cardShare)return;b.dataset.cardShare='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const card=document.querySelector('#reservations .booking:not([style*="display: none"]),#reservations .reservation-card:not([style*="display: none"])');if(card)modal(card)},true)})}
function boot(){styles();installReservationButtons();interceptTop();new MutationObserver(()=>{installReservationButtons();interceptTop()}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();