(()=>{'use strict';
const LABELS={home:'Início',reservations:'Reservas',calendar:'Calendário',expenses:'Despesas',reports:'Relatórios'};
const HTML2CANVAS='https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js';
const TARGET_WIDTH=390, PAGE_RATIO=844/390, NAV_HEIGHT=72;
function activeScreen(){return document.querySelector('.app-screen:not([hidden])')?.dataset.screenPanel||'home'}
function safeName(s){return String(s||'pagina').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'')}
function loadHtml2Canvas(){if(window.html2canvas)return Promise.resolve(window.html2canvas);return new Promise((resolve,reject)=>{let s=document.querySelector('script[data-stay-html2canvas]');if(s){s.addEventListener('load',()=>resolve(window.html2canvas),{once:true});s.addEventListener('error',()=>reject(new Error('Não foi possível carregar o capturador de imagem.')),{once:true});return;}s=document.createElement('script');s.src=HTML2CANVAS;s.async=true;s.dataset.stayHtml2canvas='1';s.onload=()=>window.html2canvas?resolve(window.html2canvas):reject(new Error('Capturador não carregou.'));s.onerror=()=>reject(new Error('Não foi possível carregar o capturador de imagem.'));document.head.appendChild(s);});}
function resizeCanvas(source,targetWidth){if(source.width===targetWidth)return source;const scale=targetWidth/source.width;const canvas=document.createElement('canvas');canvas.width=targetWidth;canvas.height=Math.max(1,Math.round(source.height*scale));const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(source,0,0,canvas.width,canvas.height);return canvas}
function hideShareControls(){const old=document.getElementById('stay-share-capture-style');if(old)old.remove();const style=document.createElement('style');style.id='stay-share-capture-style';style.textContent='.stay-share-pages{display:none!important}';document.head.appendChild(style);return()=>style.remove()}
async function captureLive(){const html2canvas=await loadHtml2Canvas();const restore=hideShareControls();try{await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const container=document.querySelector('.container');if(!container)throw new Error('Conteúdo do aplicativo não encontrado.');const raw=await html2canvas(container,{backgroundColor:'#f4f7fb',scale:1.5,useCORS:true,allowTaint:false,logging:false,scrollX:0,scrollY:-window.scrollY,windowWidth:document.documentElement.clientWidth,windowHeight:Math.max(container.scrollHeight,document.documentElement.clientHeight),removeContainer:true});let nav=null;const navEl=document.querySelector('.app-nav');if(navEl){const navRaw=await html2canvas(navEl,{backgroundColor:'#ffffff',scale:1.5,useCORS:true,allowTaint:false,logging:false,scrollX:0,scrollY:0,windowWidth:document.documentElement.clientWidth,windowHeight:navEl.scrollHeight||80,removeContainer:true});nav=resizeCanvas(navRaw,TARGET_WIDTH)}return{content:resizeCanvas(raw,TARGET_WIDTH),nav};}finally{restore()}}
function splitCanvas(content,nav){const pageHeight=Math.round(TARGET_WIDTH*PAGE_RATIO);const usable=pageHeight-(nav?NAV_HEIGHT:0);const total=Math.max(1,Math.ceil(content.height/usable));const pages=[];for(let i=0;i<total;i++){const sy=i*usable;const sh=Math.min(usable,content.height-sy);const page=document.createElement('canvas');page.width=TARGET_WIDTH;page.height=pageHeight;const ctx=page.getContext('2d');ctx.fillStyle='#f4f7fb';ctx.fillRect(0,0,page.width,page.height);ctx.drawImage(content,0,sy,content.width,sh,0,0,TARGET_WIDTH,sh);if(nav){ctx.fillStyle='#fff';ctx.fillRect(0,pageHeight-NAV_HEIGHT,TARGET_WIDTH,NAV_HEIGHT);ctx.drawImage(nav,0,0,nav.width,nav.height,0,pageHeight-NAV_HEIGHT,TARGET_WIDTH,NAV_HEIGHT)}ctx.fillStyle='rgba(15,23,42,.42)';ctx.font='600 11px -apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif';ctx.textAlign='right';ctx.fillText(`Página ${i+1} de ${total}`,page.width-12,page.height-(nav?NAV_HEIGHT+10:12));ctx.textAlign='left';pages.push(page)}return pages}
function blob(canvas){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Não foi possível gerar a imagem.')),'image/png',.95))}
async function share(){const screen=activeScreen();const label=LABELS[screen]||'Stay in Control';const shot=await captureLive();const pages=splitCanvas(shot.content,shot.nav);const files=[];for(let i=0;i<pages.length;i++){const b=await blob(pages[i]);files.push(new File([b],`Stay-in-Control-${safeName(label)}-tela-${i+1}.png`,{type:'image/png'}))}const payload={title:`${label} - Stay in Control 1.0`,files};if(navigator.share&&(!navigator.canShare||navigator.canShare(payload))){await navigator.share(payload);return;}for(const f of files){const a=document.createElement('a');a.href=URL.createObjectURL(f);a.download=f.name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}}
function install(){document.querySelectorAll('.app-screen').forEach(screen=>{if(screen.querySelector(':scope > .stay-share-pages'))return;const b=document.createElement('button');b.type='button';b.className='button button-secondary stay-share-pages no-print';b.textContent='↗ Compartilhar';b.style.cssText='font-size:13px;padding:8px 12px;min-height:auto;margin:8px 0 12px auto;display:block';b.addEventListener('click',()=>share().catch(e=>alert('Não foi possível compartilhar: '+e.message)));screen.insertBefore(b,screen.firstChild)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();