(() => {
  'use strict';
  const AUTH_KEY='ap207-auth-profile-v1';
  const INVITES_KEY='stay-control-invitations-v1';
  const PROPS_KEY='ap207-dashboard-properties-v1';
  const REDIRECT_URL='https://raw.githack.com/marcelinhone-code/Ap207-dashboard-/visual-share-working-20260818/invite.html';
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
  const auth=()=>read(AUTH_KEY,null), role=()=>auth()?.profile?.role;
  const canInvite=()=>['super_admin','admin'].includes(role());
  const saveInvites=(items)=>localStorage.setItem(INVITES_KEY,JSON.stringify(items));
  function properties(){return read(PROPS_KEY,{properties:[]}).properties||[]}
  function visibleProperties(){const a=auth(),ps=properties();if(a?.profile?.role==='super_admin')return ps;const allowed=new Set(a?.propertyIds||[]);return ps.filter(p=>allowed.has(p.id));}
  function canManage(invite){const a=auth();return !!a?.profile&&(a.profile.role==='super_admin'||(a.profile.role==='admin'&&invite.createdBy===a.profile.id));}
  function styles(){if(document.getElementById('stayUserStyles'))return;const s=document.createElement('style');s.id='stayUserStyles';s.textContent=`.stay-users{margin-top:18px}.stay-user-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:16px;padding-top:16px;border-top:1px solid #dde3ea}.stay-user-form .wide{grid-column:1/-1}.stay-user-list{display:grid;gap:10px;margin-top:14px}.stay-user-row{padding:14px;border:1px solid #e2e8f0;border-radius:14px;background:#fff;display:grid;gap:10px}.stay-user-row small{color:#64748b;line-height:1.45}.stay-user-row-actions{display:flex;gap:8px;flex-wrap:wrap}.stay-delete-invite,.stay-send-invite,.stay-resend-invite{border:1px solid transparent;border-radius:12px;padding:10px 14px;font-weight:800;font-size:.95rem;min-height:44px}.stay-delete-invite{background:#dc2626;color:#fff}.stay-send-invite{background:#2563eb;color:#fff}.stay-resend-invite{background:#173a8f;color:#fff}.stay-status-sent{color:#166534!important;font-weight:700}.stay-checks{display:grid;gap:8px;padding:10px;border:1px solid #e2e8f0;border-radius:12px}.stay-checks label{display:flex;gap:8px;align-items:center}.stay-checks input{width:auto}.stay-success{color:#166534;font-weight:800}.stay-error{color:#b42318;font-weight:800}@media(max-width:700px){.stay-user-form{grid-template-columns:1fr}.stay-user-form .wide{grid-column:auto}.stay-delete-invite,.stay-send-invite,.stay-resend-invite{flex:1 1 125px}}`;document.head.append(s)}
  async function invokeAccess(invite,button,isResend,msg,renderList){if(!window.AP207Supabase){msg.className='wide stay-error';msg.textContent='O serviço de acesso ainda está carregando. Tente novamente em alguns segundos.';return}button.disabled=true;const old=button.textContent;button.textContent=isResend?'Reenviando…':'Enviando…';msg.className='wide';msg.textContent=isResend?'Reenviando acesso…':'Enviando primeiro acesso…';try{const redirectTo=`${REDIRECT_URL}?invite=1&v=${Date.now()}`;const body={name:invite.name,email:invite.email,role:invite.role,propertyIds:invite.propertyIds,redirectTo,resend:isResend};const {data,error}=await window.AP207Supabase.functions.invoke('invite-user',{body});if(error){let detail='';try{if(error.context&&typeof error.context.json==='function'){const b=await error.context.json();detail=String(b?.error||'')}}catch{}throw new Error(detail||error.message||'Não foi possível enviar o acesso.')}if(!data?.ok)throw new Error(String(data?.error||'Não foi possível enviar o acesso.'));invite.sentAt=new Date().toISOString();invite.status=isResend?'reset_sent':'sent';invite.sendCount=(invite.sendCount||0)+1;invite.redirectTo=redirectTo;const all=read(INVITES_KEY,[]),idx=all.findIndex(x=>x.id===invite.id);if(idx>=0)all[idx]=invite;saveInvites(all);msg.className='wide stay-success';msg.textContent=isResend?`✅ Acesso reenviado com sucesso para ${invite.email}.`:`✅ Primeiro acesso enviado com sucesso para ${invite.email}.`;renderList();}catch(err){const raw=String(err?.message||'Não foi possível enviar o acesso agora.'),d=raw.toLowerCase();msg.className='wide stay-error';msg.textContent=(d.includes('rate limit')||d.includes('too many')||d.includes('429'))?'⏳ Limite temporário do serviço de e-mail. Tente novamente em alguns minutos.':`❌ ${raw}`;button.disabled=false;button.textContent=old;}}
  function install(){if(!canInvite()||document.getElementById('stayUserSection'))return;styles();const anchor=document.getElementById('propertySettings');if(!anchor)return;const section=document.createElement('section');section.id='stayUserSection';section.className='panel stay-users';section.innerHTML=`<div class="panel-heading"><div><p class="eyebrow">Usuários e acessos</p><h2>Administradores e proprietários</h2></div><button id="stayInviteUser" class="button button-primary" type="button">+ Convidar usuário</button></div><p>Convide usuários e escolha quais propriedades poderão acessar.</p><form id="stayInviteForm" class="stay-user-form" hidden><div class="field"><label>Nome</label><input id="stayInviteName" required></div><div class="field"><label>E-mail</label><input id="stayInviteEmail" type="email" required></div><div class="field"><label>Tipo de acesso</label><select id="stayInviteRole"><option value="owner">Proprietário</option>${role()==='super_admin'?'<option value="admin">Administrador/Gestor</option>':''}</select></div><div class="field wide"><label>Propriedades liberadas</label><div id="stayInviteProperties" class="stay-checks"></div></div><p id="stayInviteMessage" class="wide" role="status" aria-live="polite"></p><div class="form-actions wide"><button class="button button-primary" type="submit">Criar convite</button><button id="stayCancelInvite" class="button button-secondary" type="button">Cancelar</button></div></form><div id="stayInviteList" class="stay-user-list"></div>`;anchor.insertAdjacentElement('afterend',section);const form=section.querySelector('#stayInviteForm'),checks=section.querySelector('#stayInviteProperties'),msg=section.querySelector('#stayInviteMessage');
    const renderChecks=()=>{checks.replaceChildren();visibleProperties().forEach(p=>{const l=document.createElement('label');l.innerHTML=`<input type="checkbox" value="${p.id}"><span>${p.unit||p.name} — ${p.name||''}</span>`;checks.append(l)})};
    const removeInvite=async(inviteId,button)=>{const all=read(INVITES_KEY,[]),invite=all.find(i=>i.id===inviteId);if(!invite||!canManage(invite)||!confirm(`Excluir ${invite.name} do Stay in Control?`))return;if(!window.AP207Supabase)return;button.disabled=true;try{const {data,error}=await window.AP207Supabase.functions.invoke('delete-user',{body:{email:invite.email}});if(error||!data?.ok)throw new Error(data?.error||error?.message||'Falha ao excluir.');saveInvites(all.filter(i=>i.id!==inviteId));msg.className='wide stay-success';msg.textContent=`✅ ${invite.name} foi excluído(a).`;renderList()}catch(e){button.disabled=false;msg.className='wide stay-error';msg.textContent=`❌ ${e.message}`}};
    const renderList=()=>{const list=section.querySelector('#stayInviteList');list.replaceChildren();const items=read(INVITES_KEY,[]).filter(i=>role()==='super_admin'||i.createdBy===auth()?.profile?.id);if(!items.length){list.innerHTML='<small>Nenhum convite criado ainda.</small>';return}items.slice().reverse().forEach(i=>{const d=document.createElement('div');d.className='stay-user-row';let status=i.status==='reset_sent'?'acesso reenviado':i.status==='sent'?'primeiro acesso enviado':'convite preparado';d.innerHTML=`<div><strong>${i.name} — ${i.role==='admin'?'Administrador':'Proprietário'}</strong><small class="${i.status==='sent'||i.status==='reset_sent'?'stay-status-sent':''}">${i.email} • ${i.propertyIds.length} propriedade(s) • ${status}</small></div>`;if(canManage(i)){const actions=document.createElement('div');actions.className='stay-user-row-actions';const sent=i.status==='sent'||i.status==='reset_sent'||(i.sendCount||0)>0;const access=document.createElement('button');access.type='button';access.className=sent?'stay-resend-invite':'stay-send-invite';access.textContent=sent?'Reenviar acesso':'Enviar acesso';access.onclick=()=>invokeAccess(i,access,sent,msg,renderList);actions.append(access);const del=document.createElement('button');del.type='button';del.className='stay-delete-invite';del.textContent='Excluir';del.onclick=()=>removeInvite(i.id,del);actions.append(del);d.append(actions)}list.append(d)})};
    section.querySelector('#stayInviteUser').onclick=()=>{renderChecks();msg.textContent='';form.hidden=false};section.querySelector('#stayCancelInvite').onclick=()=>{form.reset();form.hidden=true};form.onsubmit=e=>{e.preventDefault();const a=auth(),name=section.querySelector('#stayInviteName').value.trim(),email=section.querySelector('#stayInviteEmail').value.trim().toLowerCase(),r=section.querySelector('#stayInviteRole').value,ids=[...checks.querySelectorAll('input:checked')].map(x=>x.value);if(!name||!email||(!ids.length&&r==='owner')){msg.className='wide stay-error';msg.textContent='Preencha os dados e escolha a propriedade.';return}const all=read(INVITES_KEY,[]),existing=all.find(i=>i.email===email&&i.createdBy===a.profile.id);if(existing){existing.name=name;existing.role=r;existing.propertyIds=ids;msg.className='wide stay-success';msg.textContent='Usuário já cadastrado. Use “Reenviar acesso”.'}else{all.push({id:'invite-'+Date.now(),name,email,role:r,propertyIds:ids,createdBy:a.profile.id,status:'pending',sendCount:0,createdAt:new Date().toISOString()});msg.className='wide stay-success';msg.textContent='Convite preparado. Use “Enviar acesso” para o primeiro envio.'}saveInvites(all);renderList()};renderList()}
  function boot(){const t=setInterval(()=>{if(document.body.classList.contains('ap207-authenticated')){install();if(document.getElementById('stayUserSection'))clearInterval(t)}},250);setTimeout(()=>clearInterval(t),15000)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();