(() => {
  'use strict';
  const AUTH_KEY='ap207-auth-profile-v1';
  const INVITES_KEY='stay-control-invitations-v1';
  const PROPS_KEY='ap207-dashboard-properties-v1';
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}};
  const auth=()=>read(AUTH_KEY,null);
  const role=()=>auth()?.profile?.role;
  const canInvite=()=>['super_admin','admin'].includes(role());
  function properties(){return read(PROPS_KEY,{properties:[]}).properties||[]}
  function visibleProperties(){const a=auth();const ps=properties();if(a?.profile?.role==='super_admin')return ps;const allowed=new Set(a?.propertyIds||[]);return ps.filter(p=>allowed.has(p.id));}
  function styles(){if(document.getElementById('stayUserStyles'))return;const s=document.createElement('style');s.id='stayUserStyles';s.textContent=`.stay-users{margin-top:18px}.stay-user-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.stay-user-actions{display:flex;gap:10px;flex-wrap:wrap}.stay-user-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:16px;padding-top:16px;border-top:1px solid #dde3ea}.stay-user-form .wide{grid-column:1/-1}.stay-user-list{display:grid;gap:10px;margin-top:14px}.stay-user-row{padding:12px;border:1px solid #e2e8f0;border-radius:12px;background:#fff}.stay-user-row strong{display:block}.stay-user-row small{color:#64748b}.stay-checks{display:grid;gap:8px;padding:10px;border:1px solid #e2e8f0;border-radius:12px}.stay-checks label{display:flex;gap:8px;align-items:center}.stay-checks input{width:auto}.stay-success{color:#166534;font-weight:700}.stay-error{color:#b42318;font-weight:700}@media(max-width:700px){.stay-user-grid,.stay-user-form{grid-template-columns:1fr}.stay-user-form .wide{grid-column:auto}}`;document.head.append(s)}
  function install(){if(!canInvite()||document.getElementById('stayUserSection'))return;styles();const anchor=document.getElementById('propertySettings');if(!anchor)return;const section=document.createElement('section');section.id='stayUserSection';section.className='panel stay-users';section.innerHTML=`<div class="panel-heading"><div><p class="eyebrow">Usuários e acessos</p><h2>Administradores e proprietários</h2></div><div class="stay-user-actions"><button id="stayInviteUser" class="button button-primary" type="button">+ Convidar usuário</button></div></div><p>Convide usuários e escolha quais propriedades poderão acessar.</p><form id="stayInviteForm" class="stay-user-form" hidden><div class="field"><label for="stayInviteName">Nome</label><input id="stayInviteName" required></div><div class="field"><label for="stayInviteEmail">E-mail</label><input id="stayInviteEmail" type="email" required></div><div class="field"><label for="stayInviteRole">Tipo de acesso</label><select id="stayInviteRole"><option value="owner">Proprietário</option>${role()==='super_admin'?'<option value="admin">Administrador/Gestor</option>':''}</select></div><div class="field wide"><label>Propriedades liberadas</label><div id="stayInviteProperties" class="stay-checks"></div></div><p id="stayInviteMessage" class="wide"></p><div class="form-actions wide"><button class="button button-primary" type="submit">Criar convite</button><button id="stayCancelInvite" class="button button-secondary" type="button">Cancelar</button></div></form><div id="stayInviteList" class="stay-user-list"></div>`;anchor.insertAdjacentElement('afterend',section);
    const form=section.querySelector('#stayInviteForm'), checks=section.querySelector('#stayInviteProperties'), msg=section.querySelector('#stayInviteMessage');
    const renderChecks=()=>{checks.replaceChildren();const ps=visibleProperties();if(!ps.length){checks.textContent='Nenhuma propriedade disponível.';return}ps.forEach(p=>{const l=document.createElement('label');l.innerHTML=`<input type="checkbox" value="${p.id}"><span>${p.unit||p.name} — ${p.name||''}</span>`;checks.append(l)})};
    const renderList=()=>{const list=section.querySelector('#stayInviteList');list.replaceChildren();const items=read(INVITES_KEY,[]).filter(i=>role()==='super_admin'||i.createdBy===auth()?.profile?.id);if(!items.length){list.innerHTML='<small>Nenhum convite criado ainda.</small>';return}items.slice().reverse().forEach(i=>{const d=document.createElement('div');d.className='stay-user-row';d.innerHTML=`<strong>${i.name} — ${i.role==='admin'?'Administrador':'Proprietário'}</strong><small>${i.email} • ${i.propertyIds.length} propriedade(s) • convite pendente</small>`;list.append(d)})};
    section.querySelector('#stayInviteUser').onclick=()=>{renderChecks();msg.textContent='';form.hidden=false;form.scrollIntoView({behavior:'smooth',block:'nearest'})};
    section.querySelector('#stayCancelInvite').onclick=()=>{form.reset();form.hidden=true};
    form.onsubmit=(e)=>{e.preventDefault();const a=auth();const name=section.querySelector('#stayInviteName').value.trim(),email=section.querySelector('#stayInviteEmail').value.trim().toLowerCase(),r=section.querySelector('#stayInviteRole').value;const ids=[...checks.querySelectorAll('input:checked')].map(x=>x.value);if(!name||!email){msg.className='wide stay-error';msg.textContent='Preencha nome e e-mail.';return}if(r==='admin'&&a?.profile?.role!=='super_admin'){msg.className='wide stay-error';msg.textContent='Somente o Super Administrador pode convidar administradores.';return}if(r==='owner'&&!ids.length){msg.className='wide stay-error';msg.textContent='Escolha pelo menos uma propriedade para o proprietário.';return}const all=read(INVITES_KEY,[]);all.push({id:'invite-'+Date.now(),name,email,role:r,propertyIds:ids,createdBy:a.profile.id,status:'pending',createdAt:new Date().toISOString()});localStorage.setItem(INVITES_KEY,JSON.stringify(all));msg.className='wide stay-success';msg.textContent='Convite preparado. Na próxima etapa vamos ligar este cadastro ao envio real por e-mail pelo Supabase.';renderList();};renderList();}
  function boot(){const t=setInterval(()=>{if(document.body.classList.contains('ap207-authenticated')){install();if(document.getElementById('stayUserSection'))clearInterval(t)}},250);setTimeout(()=>clearInterval(t),15000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();